import {
  LucideBold,
  LucideItalic,
  LucideUnderline,
  LucideStrikethrough,
  LucideCode,
  LucideLink,
  LucideImage,
  LucideList,
  LucideListOrdered,
  LucideQuote,
  LucideMinus,
  LucideUndo2,
  LucideRedo2,
  LucideHeading1,
  LucideHeading2,
  LucideHeading3,
  LucideSquareCode,
  type LucideIcon,
} from '@lucide/angular';
import type { EditorToolbarItem, EditorToolbarPreset } from './editor.types';

/** Lucide icon constant for each toolbar item. Keep in one place for maintainability. */
export const TOOLBAR_ICONS: Record<Exclude<EditorToolbarItem, 'divider'>, LucideIcon> = {
  bold: LucideBold,
  italic: LucideItalic,
  underline: LucideUnderline,
  strike: LucideStrikethrough,
  code: LucideCode,
  link: LucideLink,
  image: LucideImage,
  heading1: LucideHeading1,
  heading2: LucideHeading2,
  heading3: LucideHeading3,
  bulletList: LucideList,
  orderedList: LucideListOrdered,
  blockquote: LucideQuote,
  codeBlock: LucideSquareCode,
  horizontalRule: LucideMinus,
  undo: LucideUndo2,
  redo: LucideRedo2,
};

/** ARIA label per item. Exposed so consumers can localize. */
export const TOOLBAR_LABELS: Record<Exclude<EditorToolbarItem, 'divider'>, string> = {
  bold: 'Bold',
  italic: 'Italic',
  underline: 'Underline',
  strike: 'Strikethrough',
  code: 'Inline code',
  link: 'Link',
  image: 'Image',
  heading1: 'Heading 1',
  heading2: 'Heading 2',
  heading3: 'Heading 3',
  bulletList: 'Bullet list',
  orderedList: 'Ordered list',
  blockquote: 'Blockquote',
  codeBlock: 'Code block',
  horizontalRule: 'Divider',
  undo: 'Undo',
  redo: 'Redo',
};

export const TOOLBAR_PRESETS: Record<EditorToolbarPreset, readonly EditorToolbarItem[]> = {
  none: [],
  minimal: ['bold', 'italic', 'underline', 'divider', 'link'],
  basic: ['bold', 'italic', 'underline', 'strike', 'divider', 'bulletList', 'orderedList', 'divider', 'link', 'divider', 'undo', 'redo'],
  full: [
    'heading1',
    'heading2',
    'heading3',
    'divider',
    'bold',
    'italic',
    'underline',
    'strike',
    'code',
    'divider',
    'bulletList',
    'orderedList',
    'blockquote',
    'codeBlock',
    'horizontalRule',
    'divider',
    'link',
    'image',
    'divider',
    'undo',
    'redo',
  ],
};

export const TOOLBAR_ICON_COMPONENTS = [
  LucideBold,
  LucideItalic,
  LucideUnderline,
  LucideStrikethrough,
  LucideCode,
  LucideLink,
  LucideImage,
  LucideList,
  LucideListOrdered,
  LucideQuote,
  LucideMinus,
  LucideUndo2,
  LucideRedo2,
  LucideHeading1,
  LucideHeading2,
  LucideHeading3,
  LucideSquareCode,
] as const;
