import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideToast, provideAlert, provideHkTheme, provideFormState } from '@hakistack/ng-daisyui';
import {
  provideLucideIcons,
  provideLucideConfig,
  LucideRocket,
  LucideDownload,
  LucideLightbulb,
  LucideFileInput,
  LucideListOrdered,
  LucideTable,
  LucideListTree,
  LucideGitBranch,
  LucideNetwork,
  LucideScrollText,
  LucideTextCursorInput,
  LucideChevronDown,
  LucideCalendar,
  LucideClock,
  LucideFileText,
  LucidePanelTop,
  LucideBell,
  LucideMessageSquareWarning,
  LucidePanelTopOpen,
  LucideSparkles,
  LucideArrowRight,
  LucidePalette,
  LucideChevronsUpDown,
  LucideMenu,
} from '@lucide/angular';

import { routes } from './app.routes';
import { providePipes } from '../../../hakistack/ng-daisyui/src/lib/services/pipe-registry.service';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideHkTheme('daisyui-v5'),
    providePipes(),
    provideRouter(routes),
    provideToast(),
    provideAlert(),
    provideFormState({ mode: 'localStorage' }),
    provideLucideConfig({ size: 20, strokeWidth: 1.75 }),
    provideLucideIcons(
      LucideRocket,
      LucideDownload,
      LucideLightbulb,
      LucideFileInput,
      LucideListOrdered,
      LucideTable,
      LucideListTree,
      LucideGitBranch,
      LucideNetwork,
      LucideScrollText,
      LucideTextCursorInput,
      LucideChevronDown,
      LucideCalendar,
      LucideClock,
      LucideFileText,
      LucidePanelTop,
      LucideBell,
      LucideMessageSquareWarning,
      LucidePanelTopOpen,
      LucideSparkles,
      LucideArrowRight,
      LucidePalette,
      LucideChevronsUpDown,
      LucideMenu,
    ),
  ],
};
