// Auto-generated by scripts/build-pdfium-worker.mjs. Do NOT commit changes.
// This committed placeholder lets the loader + library compile before the
// worker is built. A real build (after vendoring pdfium.js/pdfium.wasm here and
// running `npm run engine:build`) overwrites it with the bundled, self-contained
// worker source (pdfium + pdf_engine wasm embedded) — large, regenerated, not
// for committing.
//
// Lives under engine/pdfium/ (NOT src/lib/wasm/) on purpose: `npm run
// engine:build` rm -rf's the whole src/lib/wasm/ tree, which would delete the
// vendored binary + this file. See PDFIUM_ENGINE.md §9b.
export const PDFIUM_WORKER_SRC = '';
