// @ts-nocheck
/* eslint-disable */
// Auto-generated by scripts/build-wasm.mjs from engine_wasm.js. Do not edit.
/* @ts-self-types="./engine_wasm.d.ts" */

/**
 * Handle to an ingested dataset. Hold one per table-component instance and
 * call [`WasmDataset::free`] in `ngOnDestroy` to release the WASM-heap memory.
 */
export class WasmDataset {
  static __wrap(ptr) {
    const obj = Object.create(WasmDataset.prototype);
    obj.__wbg_ptr = ptr;
    WasmDatasetFinalization.register(obj, obj.__wbg_ptr, obj);
    return obj;
  }
  __destroy_into_raw() {
    const ptr = this.__wbg_ptr;
    this.__wbg_ptr = 0;
    WasmDatasetFinalization.unregister(this);
    return ptr;
  }
  free() {
    const ptr = this.__destroy_into_raw();
    wasm.__wbg_wasmdataset_free(ptr, 0);
  }
  /**
   * Compute one aggregate over the given column.
   *
   * `indices == null` ⇒ aggregate over the entire dataset
   * (`RowSet::All`). Otherwise the aggregate runs over the supplied subset.
   * @param {number} column
   * @param {Uint32Array | null | undefined} indices
   * @param {any} agg
   * @returns {any}
   */
  aggregate(column, indices, agg) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.wasmdataset_aggregate(retptr, this.__wbg_ptr, column, isLikeNone(indices) ? 0 : addHeapObject(indices), addHeapObject(agg));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return takeObject(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * Apply filters, AND-combined. Empty filter list ⇒ all rows pass.
   * Returns row indices in source order.
   * @param {any} filters
   * @returns {Uint32Array}
   */
  filter(filters) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.wasmdataset_filter(retptr, this.__wbg_ptr, addHeapObject(filters));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return takeObject(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * Multi-level group. Returns a tree of `WireGroup` nodes.
   * `columns` is the chain of grouping fields (e.g. `[country_id, state_id]`).
   * `indices == null` ⇒ group across the entire dataset.
   * @param {Uint32Array} columns
   * @param {Uint32Array | null} [indices]
   * @returns {any}
   */
  group(columns, indices) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      const ptr0 = passArray32ToWasm0(columns, wasm.__wbindgen_export);
      const len0 = WASM_VECTOR_LEN;
      wasm.wasmdataset_group(retptr, this.__wbg_ptr, ptr0, len0, isLikeNone(indices) ? 0 : addHeapObject(indices));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return takeObject(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * Build a dataset from columnar arrays.
   *
   * Arguments:
   * - `n_rows`: total row count (every column array must match)
   * - `schema`: `Array<{ id: number, kind: 'text' | 'number' | 'bool' | 'date' }>`
   * - `columns`: `Array` of per-column payloads, same order and length as
   *   `schema`. Wire shape depends on column kind:
   *     - `text` ⇒ `(string | null)[]` (serde path — strings have no
   *       packed typed-array form)
   *     - `number` ⇒ `{ values: Float64Array, validity: Uint8Array }`
   *     - `bool` ⇒ `{ values: Uint8Array (0/1), validity: Uint8Array }`
   *     - `date` ⇒ `{ values: Float64Array (ms-epoch), validity: Uint8Array }`
   *
   * The typed-array pairs are bulk-copied into Rust via `TypedArray::to_vec`
   * (one memcpy per column), then the validity `Uint8Array` is packed into
   * a `Bitset` for word-at-a-time filter scans. This skips the per-row
   * `Option<X>` wrapping that the prior all-serde path paid for —
   * `serde_wasm_bindgen::from_value` allocated `N` heap Options per
   * numeric column, dominating ingest time on large datasets.
   * @param {number} n_rows
   * @param {any} schema
   * @param {Array<any>} columns
   * @returns {WasmDataset}
   */
  static ingest(n_rows, schema, columns) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.wasmdataset_ingest(retptr, n_rows, addHeapObject(schema), addHeapObject(columns));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return WasmDataset.__wrap(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * @returns {number}
   */
  n_rows() {
    const ret = wasm.wasmdataset_n_rows(this.__wbg_ptr);
    return ret >>> 0;
  }
  /**
   * Apply a global multi-column search and return the matching-row mask.
   * Empty term ⇒ empty result (caller composes with the filter mask, where
   * "no search" means "no constraint added", not "everything matches").
   * @param {any} spec
   * @returns {Uint32Array}
   */
  search(spec) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.wasmdataset_search(retptr, this.__wbg_ptr, addHeapObject(spec));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return takeObject(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * Sort the given indices by a multi-tier sort spec, return the new order.
   * Stable sort, so callers can chain by re-sorting the previous output.
   * @param {Uint32Array} indices
   * @param {any} specs
   * @returns {Uint32Array}
   */
  sort(indices, specs) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.wasmdataset_sort(retptr, this.__wbg_ptr, addBorrowedObject(indices), addHeapObject(specs));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return takeObject(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
      heap[stack_pointer++] = undefined;
    }
  }
}
if (Symbol.dispose) WasmDataset.prototype[Symbol.dispose] = WasmDataset.prototype.free;

/**
 * Handle to a form-engine instance. Owns the immutable schema, the
 * per-form runtime state (value map + visibility / required / disabled
 * bitsets), and the JS predicate registry for `function`-op conditions.
 *
 * One handle per `<hk-dynamic-form>`; call `free()` (auto-generated by
 * wasm-bindgen) in `ngOnDestroy` to release WASM-heap memory.
 */
export class WasmFormEngine {
  static __wrap(ptr) {
    const obj = Object.create(WasmFormEngine.prototype);
    obj.__wbg_ptr = ptr;
    WasmFormEngineFinalization.register(obj, obj.__wbg_ptr, obj);
    return obj;
  }
  __destroy_into_raw() {
    const ptr = this.__wbg_ptr;
    this.__wbg_ptr = 0;
    WasmFormEngineFinalization.unregister(this);
    return ptr;
  }
  free() {
    const ptr = this.__destroy_into_raw();
    wasm.__wbg_wasmformengine_free(ptr, 0);
  }
  /**
   * @returns {number}
   */
  field_count() {
    const ret = wasm.wasmformengine_field_count(this.__wbg_ptr);
    return ret >>> 0;
  }
  /**
   * Resolve a field name to its index. Returns `u32::MAX` for unknown
   * names — JS contract: the adapter caches this map once and never
   * hits the lookup on the hot path.
   * @param {string} name
   * @returns {number}
   */
  index_of(name) {
    const ptr0 = passStringToWasm0(name, wasm.__wbindgen_export, wasm.__wbindgen_export2);
    const len0 = WASM_VECTOR_LEN;
    const ret = wasm.wasmformengine_index_of(this.__wbg_ptr, ptr0, len0);
    return ret >>> 0;
  }
  /**
   * Build a new engine from a `WireFormSchema`. The schema is uploaded
   * once; per-keystroke calls only ship value updates.
   * @param {any} schema
   * @returns {WasmFormEngine}
   */
  static ingest(schema) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.wasmformengine_ingest(retptr, addHeapObject(schema));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return WasmFormEngine.__wrap(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * @param {number} field
   * @returns {boolean}
   */
  is_disabled(field) {
    const ret = wasm.wasmformengine_is_disabled(this.__wbg_ptr, field);
    return ret !== 0;
  }
  /**
   * @param {number} field
   * @returns {boolean}
   */
  is_required(field) {
    const ret = wasm.wasmformengine_is_required(this.__wbg_ptr, field);
    return ret !== 0;
  }
  /**
   * @param {number} field
   * @returns {boolean}
   */
  is_visible(field) {
    const ret = wasm.wasmformengine_is_visible(this.__wbg_ptr, field);
    return ret !== 0;
  }
  /**
   * Full pass. Used by the TS adapter when an external signal moves
   * (no `formValues` diff available) and `function`-predicate fields
   * must be re-checked alongside every other conditional field.
   * @returns {Uint32Array}
   */
  recompute_all() {
    const ret = wasm.wasmformengine_recompute_all(this.__wbg_ptr);
    return takeObject(ret);
  }
  /**
   * Register a JS function-operator predicate. `id` is the value the
   * schema's `WireFormValue::Callback { id }` will refer to; the
   * function is zero-arg and returns boolean.
   * @param {number} id
   * @param {Function} evaluator
   */
  register_predicate(id, evaluator) {
    wasm.wasmformengine_register_predicate(this.__wbg_ptr, id, addHeapObject(evaluator));
  }
  /**
   * Push a single field value. Returns a packed `Uint32Array` of
   * `(kind, field, payload)` triples — empty when the value is the
   * same as the previous one or no observable transition occurred.
   * @param {number} field
   * @param {any} value
   * @returns {Uint32Array}
   */
  set_value(field, value) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.wasmformengine_set_value(retptr, this.__wbg_ptr, field, addHeapObject(value));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return takeObject(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * Batch write: array of `[field_idx, value]` pairs. Single dep-graph
   * walk afterward, so two changes that touch the same downstream
   * field only emit one transition event.
   * @param {any} pairs
   * @returns {Uint32Array}
   */
  set_values(pairs) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.wasmformengine_set_values(retptr, this.__wbg_ptr, addHeapObject(pairs));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return takeObject(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * @param {number} id
   */
  unregister_predicate(id) {
    wasm.wasmformengine_unregister_predicate(this.__wbg_ptr, id);
  }
}
if (Symbol.dispose) WasmFormEngine.prototype[Symbol.dispose] = WasmFormEngine.prototype.free;

/**
 * Handle to a fuzzy-search index. Powers `<hk-command-palette>` and
 * `<hk-select>` per-keystroke ranking, replacing Fuse.js. Each input string
 * becomes one searchable item; query results are returned as
 * `(item_index, score)` pairs sorted by score descending.
 */
export class WasmFuzzyIndex {
  static __wrap(ptr) {
    const obj = Object.create(WasmFuzzyIndex.prototype);
    obj.__wbg_ptr = ptr;
    WasmFuzzyIndexFinalization.register(obj, obj.__wbg_ptr, obj);
    return obj;
  }
  __destroy_into_raw() {
    const ptr = this.__wbg_ptr;
    this.__wbg_ptr = 0;
    WasmFuzzyIndexFinalization.unregister(this);
    return ptr;
  }
  free() {
    const ptr = this.__destroy_into_raw();
    wasm.__wbg_wasmfuzzyindex_free(ptr, 0);
  }
  /**
   * Build an index from a flat list of strings. Index `i` in `items`
   * is the index returned by `search`.
   * @param {string[]} items
   * @returns {WasmFuzzyIndex}
   */
  static ingest(items) {
    const ptr0 = passArrayJsValueToWasm0(items, wasm.__wbindgen_export);
    const len0 = WASM_VECTOR_LEN;
    const ret = wasm.wasmfuzzyindex_ingest(ptr0, len0);
    return WasmFuzzyIndex.__wrap(ret);
  }
  /**
   * @returns {number}
   */
  n_items() {
    const ret = wasm.wasmfuzzyindex_n_items(this.__wbg_ptr);
    return ret >>> 0;
  }
  /**
   * Run a query. Returns a packed `Uint32Array` where consecutive pairs
   * are `(item_index, score)`. Length is `2 × match_count`. JS reads in
   * groups of two and decodes into `{ index, score }` records.
   *
   * `opts.max_results === 0` means "no cap" (all matches returned).
   * @param {string} query
   * @param {any} opts
   * @returns {Uint32Array}
   */
  search(query, opts) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      const ptr0 = passStringToWasm0(query, wasm.__wbindgen_export, wasm.__wbindgen_export2);
      const len0 = WASM_VECTOR_LEN;
      wasm.wasmfuzzyindex_search(retptr, this.__wbg_ptr, ptr0, len0, addHeapObject(opts));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return takeObject(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
}
if (Symbol.dispose) WasmFuzzyIndex.prototype[Symbol.dispose] = WasmFuzzyIndex.prototype.free;

/**
 * Handle to a PDF in-document search index. Pages are added lazily as PDF.js
 * produces text content via `getTextContent()`. Searches scan every ingested
 * page and return packed `(page, char_start, char_len)` triples that the
 * highlight painter resolves to text-layer DOM spans via [`resolve_hit`].
 */
export class WasmPdfIndex {
  static __wrap(ptr) {
    const obj = Object.create(WasmPdfIndex.prototype);
    obj.__wbg_ptr = ptr;
    WasmPdfIndexFinalization.register(obj, obj.__wbg_ptr, obj);
    return obj;
  }
  __destroy_into_raw() {
    const ptr = this.__wbg_ptr;
    this.__wbg_ptr = 0;
    WasmPdfIndexFinalization.unregister(this);
    return ptr;
  }
  free() {
    const ptr = this.__destroy_into_raw();
    wasm.__wbg_wasmpdfindex_free(ptr, 0);
  }
  /**
   * Ingest a page's text items. `text_items` is the array PDF.js's
   * `getTextContent().items.map(it => it.str)` produces — same order as
   * the text-layer DOM spans, so item indices map back 1-to-1.
   * @param {number} page
   * @param {string[]} text_items
   */
  add_page(page, text_items) {
    const ptr0 = passArrayJsValueToWasm0(text_items, wasm.__wbindgen_export);
    const len0 = WASM_VECTOR_LEN;
    wasm.wasmpdfindex_add_page(this.__wbg_ptr, page, ptr0, len0);
  }
  /**
   * @param {number} page
   * @returns {boolean}
   */
  has_page(page) {
    const ret = wasm.wasmpdfindex_has_page(this.__wbg_ptr, page);
    return ret !== 0;
  }
  /**
   * @returns {number}
   */
  n_pages() {
    const ret = wasm.wasmpdfindex_n_pages(this.__wbg_ptr);
    return ret >>> 0;
  }
  /**
   * Build an empty index for `page_count` pages. All pages start
   * uningested; call [`add_page`] as PDF.js delivers each page's text.
   * @param {number} page_count
   * @returns {WasmPdfIndex}
   */
  static new(page_count) {
    const ret = wasm.wasmpdfindex_new(page_count);
    return WasmPdfIndex.__wrap(ret);
  }
  /**
   * Resolve a hit to its text-item indices. Returns a 4-element
   * `Uint32Array`: `(item_start, item_end, intra_start, intra_end)`.
   * Empty array when the hit can't be resolved (page uningested, etc.).
   * @param {number} page
   * @param {number} char_start
   * @param {number} char_len
   * @returns {Uint32Array}
   */
  resolve_hit(page, char_start, char_len) {
    const ret = wasm.wasmpdfindex_resolve_hit(this.__wbg_ptr, page, char_start, char_len);
    return takeObject(ret);
  }
  /**
   * Run a search across every ingested page. Returns a packed
   * `Uint32Array` where each consecutive triple is
   * `(page, char_start, char_len)`. Length is `3 × hit_count`.
   * @param {string} query
   * @param {any} opts
   * @returns {Uint32Array}
   */
  search(query, opts) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      const ptr0 = passStringToWasm0(query, wasm.__wbindgen_export, wasm.__wbindgen_export2);
      const len0 = WASM_VECTOR_LEN;
      wasm.wasmpdfindex_search(retptr, this.__wbg_ptr, ptr0, len0, addHeapObject(opts));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return takeObject(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
}
if (Symbol.dispose) WasmPdfIndex.prototype[Symbol.dispose] = WasmPdfIndex.prototype.free;

/**
 * Handle to an ingested tree. Mirror of `WasmDataset` but for hierarchical
 * data: filter / flatten / cascade work on node indices; the JS side keeps
 * its original tree by reference and resolves indices back to nodes.
 */
export class WasmTree {
  static __wrap(ptr) {
    const obj = Object.create(WasmTree.prototype);
    obj.__wbg_ptr = ptr;
    WasmTreeFinalization.register(obj, obj.__wbg_ptr, obj);
    return obj;
  }
  __destroy_into_raw() {
    const ptr = this.__wbg_ptr;
    this.__wbg_ptr = 0;
    WasmTreeFinalization.unregister(this);
    return ptr;
  }
  free() {
    const ptr = this.__destroy_into_raw();
    wasm.__wbg_wasmtree_free(ptr, 0);
  }
  /**
   * Cascade up from `changed`. Returns a packed `Uint32Array` of
   * `(ancestor_idx, state)` pairs — `state` ∈ {0=clear, 1=selected, 2=indeterminate}.
   * Length = `2 * ancestor_count`.
   * @param {Uint32Array} selected
   * @param {number} changed
   * @returns {Uint32Array}
   */
  cascade_up(selected, changed) {
    try {
      const ret = wasm.wasmtree_cascade_up(this.__wbg_ptr, addBorrowedObject(selected), changed);
      return takeObject(ret);
    } finally {
      heap[stack_pointer++] = undefined;
    }
  }
  /**
   * Apply a label filter and return the visibility mask packed as a
   * `Uint32Array` of *visible* node indices in source order.
   * @param {any} spec
   * @returns {Uint32Array}
   */
  filter(spec) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      wasm.wasmtree_filter(retptr, this.__wbg_ptr, addHeapObject(spec));
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return takeObject(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * Flatten the tree, given which nodes are visible and which are expanded.
   * Both inputs are `Uint32Array`s of node indices.
   *
   * Returns a packed `Uint32Array` of `(node, depth, has_children)` triples
   * in DFS preorder. Length is `3 * row_count`. JS reads in groups of three.
   * @param {Uint32Array} visible
   * @param {Uint32Array} expanded
   * @returns {Uint32Array}
   */
  flatten(visible, expanded) {
    try {
      const ret = wasm.wasmtree_flatten(this.__wbg_ptr, addBorrowedObject(visible), addBorrowedObject(expanded));
      return takeObject(ret);
    } finally {
      heap[stack_pointer++] = undefined;
      heap[stack_pointer++] = undefined;
    }
  }
  /**
   * Build a tree from a flat DFS-preorder representation.
   *
   * `labels[i]` is the i-th node's display label, `depths[i]` is its
   * depth (0 = root). The JS side walks its hierarchical structure once
   * and produces these flat arrays — much cheaper than nested objects
   * across the boundary.
   * @param {string[]} labels
   * @param {Uint8Array} depths
   * @returns {WasmTree}
   */
  static ingest(labels, depths) {
    try {
      const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
      const ptr0 = passArrayJsValueToWasm0(labels, wasm.__wbindgen_export);
      const len0 = WASM_VECTOR_LEN;
      const ptr1 = passArray8ToWasm0(depths, wasm.__wbindgen_export);
      const len1 = WASM_VECTOR_LEN;
      wasm.wasmtree_ingest(retptr, ptr0, len0, ptr1, len1);
      var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
      var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
      var r2 = getDataViewMemory0().getInt32(retptr + 4 * 2, true);
      if (r2) {
        throw takeObject(r1);
      }
      return WasmTree.__wrap(r0);
    } finally {
      wasm.__wbindgen_add_to_stack_pointer(16);
    }
  }
  /**
   * O(1) ancestor test using the arena's pre-computed Euler-tour intervals.
   * @param {number} root
   * @param {number} candidate
   * @returns {boolean}
   */
  is_descendant(root, candidate) {
    const ret = wasm.wasmtree_is_descendant(this.__wbg_ptr, root, candidate);
    return ret !== 0;
  }
  /**
   * @returns {number}
   */
  n_nodes() {
    const ret = wasm.wasmtree_n_nodes(this.__wbg_ptr);
    return ret >>> 0;
  }
  /**
   * Return every descendant of `root` in DFS preorder, including `root`.
   * @param {number} root
   * @returns {Uint32Array}
   */
  select_descendants(root) {
    const ret = wasm.wasmtree_select_descendants(this.__wbg_ptr, root);
    return takeObject(ret);
  }
}
if (Symbol.dispose) WasmTree.prototype[Symbol.dispose] = WasmTree.prototype.free;

/**
 * Engine version string. Useful smoke-test export and debugging aid.
 * @returns {string}
 */
export function engine_version() {
  let deferred1_0;
  let deferred1_1;
  try {
    const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
    wasm.engine_version(retptr);
    var r0 = getDataViewMemory0().getInt32(retptr + 4 * 0, true);
    var r1 = getDataViewMemory0().getInt32(retptr + 4 * 1, true);
    deferred1_0 = r0;
    deferred1_1 = r1;
    return getStringFromWasm0(r0, r1);
  } finally {
    wasm.__wbindgen_add_to_stack_pointer(16);
    wasm.__wbindgen_export4(deferred1_0, deferred1_1, 1);
  }
}

/**
 * Called automatically when the module is instantiated.
 */
export function init() {
  wasm.init();
}
function __wbg_get_imports() {
  const import0 = {
    __proto__: null,
    __wbg_Error_bce6d499ff0a4aff: function (arg0, arg1) {
      const ret = Error(getStringFromWasm0(arg0, arg1));
      return addHeapObject(ret);
    },
    __wbg_Number_b7972a139bfbfdf0: function (arg0) {
      const ret = Number(getObject(arg0));
      return ret;
    },
    __wbg_String_8564e559799eccda: function (arg0, arg1) {
      const ret = String(getObject(arg1));
      const ptr1 = passStringToWasm0(ret, wasm.__wbindgen_export, wasm.__wbindgen_export2);
      const len1 = WASM_VECTOR_LEN;
      getDataViewMemory0().setInt32(arg0 + 4 * 1, len1, true);
      getDataViewMemory0().setInt32(arg0 + 4 * 0, ptr1, true);
    },
    __wbg___wbindgen_bigint_get_as_i64_410e28c7b761ad83: function (arg0, arg1) {
      const v = getObject(arg1);
      const ret = typeof v === 'bigint' ? v : undefined;
      getDataViewMemory0().setBigInt64(arg0 + 8 * 1, isLikeNone(ret) ? BigInt(0) : ret, true);
      getDataViewMemory0().setInt32(arg0 + 4 * 0, !isLikeNone(ret), true);
    },
    __wbg___wbindgen_boolean_get_2304fb8c853028c8: function (arg0) {
      const v = getObject(arg0);
      const ret = typeof v === 'boolean' ? v : undefined;
      return isLikeNone(ret) ? 0xffffff : ret ? 1 : 0;
    },
    __wbg___wbindgen_debug_string_edece8177ad01481: function (arg0, arg1) {
      const ret = debugString(getObject(arg1));
      const ptr1 = passStringToWasm0(ret, wasm.__wbindgen_export, wasm.__wbindgen_export2);
      const len1 = WASM_VECTOR_LEN;
      getDataViewMemory0().setInt32(arg0 + 4 * 1, len1, true);
      getDataViewMemory0().setInt32(arg0 + 4 * 0, ptr1, true);
    },
    __wbg___wbindgen_in_07056af4f902c445: function (arg0, arg1) {
      const ret = getObject(arg0) in getObject(arg1);
      return ret;
    },
    __wbg___wbindgen_is_bigint_aeae3893f30ed54e: function (arg0) {
      const ret = typeof getObject(arg0) === 'bigint';
      return ret;
    },
    __wbg___wbindgen_is_function_5cd60d5cf78b4eef: function (arg0) {
      const ret = typeof getObject(arg0) === 'function';
      return ret;
    },
    __wbg___wbindgen_is_object_b4593df85baada48: function (arg0) {
      const val = getObject(arg0);
      const ret = typeof val === 'object' && val !== null;
      return ret;
    },
    __wbg___wbindgen_is_string_dde0fd9020db4434: function (arg0) {
      const ret = typeof getObject(arg0) === 'string';
      return ret;
    },
    __wbg___wbindgen_is_undefined_35bb9f4c7fd651d5: function (arg0) {
      const ret = getObject(arg0) === undefined;
      return ret;
    },
    __wbg___wbindgen_jsval_eq_c0ed08b3e0f393b9: function (arg0, arg1) {
      const ret = getObject(arg0) === getObject(arg1);
      return ret;
    },
    __wbg___wbindgen_jsval_loose_eq_0ad77b7717db155c: function (arg0, arg1) {
      const ret = getObject(arg0) == getObject(arg1);
      return ret;
    },
    __wbg___wbindgen_number_get_f73a1244370fcc2c: function (arg0, arg1) {
      const obj = getObject(arg1);
      const ret = typeof obj === 'number' ? obj : undefined;
      getDataViewMemory0().setFloat64(arg0 + 8 * 1, isLikeNone(ret) ? 0 : ret, true);
      getDataViewMemory0().setInt32(arg0 + 4 * 0, !isLikeNone(ret), true);
    },
    __wbg___wbindgen_string_get_d109740c0d18f4d7: function (arg0, arg1) {
      const obj = getObject(arg1);
      const ret = typeof obj === 'string' ? obj : undefined;
      var ptr1 = isLikeNone(ret) ? 0 : passStringToWasm0(ret, wasm.__wbindgen_export, wasm.__wbindgen_export2);
      var len1 = WASM_VECTOR_LEN;
      getDataViewMemory0().setInt32(arg0 + 4 * 1, len1, true);
      getDataViewMemory0().setInt32(arg0 + 4 * 0, ptr1, true);
    },
    __wbg___wbindgen_throw_9c31b086c2b26051: function (arg0, arg1) {
      throw new Error(getStringFromWasm0(arg0, arg1));
    },
    __wbg_call_13665d9f14390edc: function () {
      return handleError(function (arg0, arg1) {
        const ret = getObject(arg0).call(getObject(arg1));
        return addHeapObject(ret);
      }, arguments);
    },
    __wbg_done_54b8da57023b7ed2: function (arg0) {
      const ret = getObject(arg0).done;
      return ret;
    },
    __wbg_entries_564a7e8b1e54ede5: function (arg0) {
      const ret = Object.entries(getObject(arg0));
      return addHeapObject(ret);
    },
    __wbg_get_3e9a707ab7d352eb: function () {
      return handleError(function (arg0, arg1) {
        const ret = Reflect.get(getObject(arg0), getObject(arg1));
        return addHeapObject(ret);
      }, arguments);
    },
    __wbg_get_98fdf51d029a75eb: function (arg0, arg1) {
      const ret = getObject(arg0)[arg1 >>> 0];
      return addHeapObject(ret);
    },
    __wbg_get_dcf82ab8aad1a593: function () {
      return handleError(function (arg0, arg1) {
        const ret = Reflect.get(getObject(arg0), getObject(arg1));
        return addHeapObject(ret);
      }, arguments);
    },
    __wbg_get_unchecked_1dfe6d05ad91d9b7: function (arg0, arg1) {
      const ret = getObject(arg0)[arg1 >>> 0];
      return addHeapObject(ret);
    },
    __wbg_get_with_ref_key_6412cf3094599694: function (arg0, arg1) {
      const ret = getObject(arg0)[getObject(arg1)];
      return addHeapObject(ret);
    },
    __wbg_instanceof_ArrayBuffer_53db37b06f6b9afe: function (arg0) {
      let result;
      try {
        result = getObject(arg0) instanceof ArrayBuffer;
      } catch (_) {
        result = false;
      }
      const ret = result;
      return ret;
    },
    __wbg_instanceof_Float64Array_3bb8295dc7055274: function (arg0) {
      let result;
      try {
        result = getObject(arg0) instanceof Float64Array;
      } catch (_) {
        result = false;
      }
      const ret = result;
      return ret;
    },
    __wbg_instanceof_Map_16f217b9a2a08d8c: function (arg0) {
      let result;
      try {
        result = getObject(arg0) instanceof Map;
      } catch (_) {
        result = false;
      }
      const ret = result;
      return ret;
    },
    __wbg_instanceof_Uint8Array_abd07d4bd221d50b: function (arg0) {
      let result;
      try {
        result = getObject(arg0) instanceof Uint8Array;
      } catch (_) {
        result = false;
      }
      const ret = result;
      return ret;
    },
    __wbg_isArray_94898ed3aad6947b: function (arg0) {
      const ret = Array.isArray(getObject(arg0));
      return ret;
    },
    __wbg_isSafeInteger_01e964d144ad3a55: function (arg0) {
      const ret = Number.isSafeInteger(getObject(arg0));
      return ret;
    },
    __wbg_iterator_1441b47f341dc34f: function () {
      const ret = Symbol.iterator;
      return addHeapObject(ret);
    },
    __wbg_length_2591a0f4f659a55c: function (arg0) {
      const ret = getObject(arg0).length;
      return ret;
    },
    __wbg_length_3a1b902b6cde9e2c: function (arg0) {
      const ret = getObject(arg0).length;
      return ret;
    },
    __wbg_length_56fcd3e2b7e0299d: function (arg0) {
      const ret = getObject(arg0).length;
      return ret;
    },
    __wbg_length_c7ce929623e7a230: function (arg0) {
      const ret = getObject(arg0).length;
      return ret;
    },
    __wbg_new_02d162bc6cf02f60: function () {
      const ret = new Object();
      return addHeapObject(ret);
    },
    __wbg_new_310879b66b6e95e1: function () {
      const ret = new Array();
      return addHeapObject(ret);
    },
    __wbg_new_7ddec6de44ff8f5d: function (arg0) {
      const ret = new Uint8Array(getObject(arg0));
      return addHeapObject(ret);
    },
    __wbg_new_with_length_f128f2c16ad4f906: function (arg0) {
      const ret = new Uint32Array(arg0 >>> 0);
      return addHeapObject(ret);
    },
    __wbg_next_2a4e19f4f5083b0f: function (arg0) {
      const ret = getObject(arg0).next;
      return addHeapObject(ret);
    },
    __wbg_next_6429a146bf756f93: function () {
      return handleError(function (arg0) {
        const ret = getObject(arg0).next();
        return addHeapObject(ret);
      }, arguments);
    },
    __wbg_prototypesetcall_272875b350b1e49b: function (arg0, arg1, arg2) {
      Float64Array.prototype.set.call(getArrayF64FromWasm0(arg0, arg1), getObject(arg2));
    },
    __wbg_prototypesetcall_303283bf37c9f014: function (arg0, arg1, arg2) {
      Uint32Array.prototype.set.call(getArrayU32FromWasm0(arg0, arg1), getObject(arg2));
    },
    __wbg_prototypesetcall_5f9bdc8d75e07276: function (arg0, arg1, arg2) {
      Uint8Array.prototype.set.call(getArrayU8FromWasm0(arg0, arg1), getObject(arg2));
    },
    __wbg_set_6be42768c690e380: function (arg0, arg1, arg2) {
      getObject(arg0)[takeObject(arg1)] = takeObject(arg2);
    },
    __wbg_set_78ea6a19f4818587: function (arg0, arg1, arg2) {
      getObject(arg0)[arg1 >>> 0] = takeObject(arg2);
    },
    __wbg_set_90474108ec025ba3: function (arg0, arg1, arg2) {
      getObject(arg0).set(getArrayU32FromWasm0(arg1, arg2));
    },
    __wbg_value_9cc0518af87a489c: function (arg0) {
      const ret = getObject(arg0).value;
      return addHeapObject(ret);
    },
    __wbindgen_cast_0000000000000001: function (arg0) {
      // Cast intrinsic for `F64 -> Externref`.
      const ret = arg0;
      return addHeapObject(ret);
    },
    __wbindgen_cast_0000000000000002: function (arg0) {
      // Cast intrinsic for `I64 -> Externref`.
      const ret = arg0;
      return addHeapObject(ret);
    },
    __wbindgen_cast_0000000000000003: function (arg0, arg1) {
      // Cast intrinsic for `Ref(String) -> Externref`.
      const ret = getStringFromWasm0(arg0, arg1);
      return addHeapObject(ret);
    },
    __wbindgen_cast_0000000000000004: function (arg0) {
      // Cast intrinsic for `U64 -> Externref`.
      const ret = BigInt.asUintN(64, arg0);
      return addHeapObject(ret);
    },
    __wbindgen_object_clone_ref: function (arg0) {
      const ret = getObject(arg0);
      return addHeapObject(ret);
    },
    __wbindgen_object_drop_ref: function (arg0) {
      takeObject(arg0);
    },
  };
  return {
    __proto__: null,
    './engine_wasm_bg.js': import0,
  };
}

const WasmDatasetFinalization =
  typeof FinalizationRegistry === 'undefined'
    ? { register: () => {}, unregister: () => {} }
    : new FinalizationRegistry((ptr) => wasm.__wbg_wasmdataset_free(ptr, 1));
const WasmFormEngineFinalization =
  typeof FinalizationRegistry === 'undefined'
    ? { register: () => {}, unregister: () => {} }
    : new FinalizationRegistry((ptr) => wasm.__wbg_wasmformengine_free(ptr, 1));
const WasmFuzzyIndexFinalization =
  typeof FinalizationRegistry === 'undefined'
    ? { register: () => {}, unregister: () => {} }
    : new FinalizationRegistry((ptr) => wasm.__wbg_wasmfuzzyindex_free(ptr, 1));
const WasmPdfIndexFinalization =
  typeof FinalizationRegistry === 'undefined'
    ? { register: () => {}, unregister: () => {} }
    : new FinalizationRegistry((ptr) => wasm.__wbg_wasmpdfindex_free(ptr, 1));
const WasmTreeFinalization =
  typeof FinalizationRegistry === 'undefined'
    ? { register: () => {}, unregister: () => {} }
    : new FinalizationRegistry((ptr) => wasm.__wbg_wasmtree_free(ptr, 1));

function addHeapObject(obj) {
  if (heap_next === heap.length) heap.push(heap.length + 1);
  const idx = heap_next;
  heap_next = heap[idx];

  heap[idx] = obj;
  return idx;
}

function addBorrowedObject(obj) {
  if (stack_pointer == 1) throw new Error('out of js stack');
  heap[--stack_pointer] = obj;
  return stack_pointer;
}

function debugString(val) {
  // primitive types
  const type = typeof val;
  if (type == 'number' || type == 'boolean' || val == null) {
    return `${val}`;
  }
  if (type == 'string') {
    return `"${val}"`;
  }
  if (type == 'symbol') {
    const description = val.description;
    if (description == null) {
      return 'Symbol';
    } else {
      return `Symbol(${description})`;
    }
  }
  if (type == 'function') {
    const name = val.name;
    if (typeof name == 'string' && name.length > 0) {
      return `Function(${name})`;
    } else {
      return 'Function';
    }
  }
  // objects
  if (Array.isArray(val)) {
    const length = val.length;
    let debug = '[';
    if (length > 0) {
      debug += debugString(val[0]);
    }
    for (let i = 1; i < length; i++) {
      debug += ', ' + debugString(val[i]);
    }
    debug += ']';
    return debug;
  }
  // Test for built-in
  const builtInMatches = /\[object ([^\]]+)\]/.exec(toString.call(val));
  let className;
  if (builtInMatches && builtInMatches.length > 1) {
    className = builtInMatches[1];
  } else {
    // Failed to match the standard '[object ClassName]'
    return toString.call(val);
  }
  if (className == 'Object') {
    // we're a user defined class or Object
    // JSON.stringify avoids problems with cycles, and is generally much
    // easier than looping through ownProperties of `val`.
    try {
      return 'Object(' + JSON.stringify(val) + ')';
    } catch (_) {
      return 'Object';
    }
  }
  // errors
  if (val instanceof Error) {
    return `${val.name}: ${val.message}\n${val.stack}`;
  }
  // TODO we could test for more things here, like `Set`s and `Map`s.
  return className;
}

function dropObject(idx) {
  if (idx < 1028) return;
  heap[idx] = heap_next;
  heap_next = idx;
}

function getArrayF64FromWasm0(ptr, len) {
  ptr = ptr >>> 0;
  return getFloat64ArrayMemory0().subarray(ptr / 8, ptr / 8 + len);
}

function getArrayU32FromWasm0(ptr, len) {
  ptr = ptr >>> 0;
  return getUint32ArrayMemory0().subarray(ptr / 4, ptr / 4 + len);
}

function getArrayU8FromWasm0(ptr, len) {
  ptr = ptr >>> 0;
  return getUint8ArrayMemory0().subarray(ptr / 1, ptr / 1 + len);
}

let cachedDataViewMemory0 = null;
function getDataViewMemory0() {
  if (
    cachedDataViewMemory0 === null ||
    cachedDataViewMemory0.buffer.detached === true ||
    (cachedDataViewMemory0.buffer.detached === undefined && cachedDataViewMemory0.buffer !== wasm.memory.buffer)
  ) {
    cachedDataViewMemory0 = new DataView(wasm.memory.buffer);
  }
  return cachedDataViewMemory0;
}

let cachedFloat64ArrayMemory0 = null;
function getFloat64ArrayMemory0() {
  if (cachedFloat64ArrayMemory0 === null || cachedFloat64ArrayMemory0.byteLength === 0) {
    cachedFloat64ArrayMemory0 = new Float64Array(wasm.memory.buffer);
  }
  return cachedFloat64ArrayMemory0;
}

function getStringFromWasm0(ptr, len) {
  return decodeText(ptr >>> 0, len);
}

let cachedUint32ArrayMemory0 = null;
function getUint32ArrayMemory0() {
  if (cachedUint32ArrayMemory0 === null || cachedUint32ArrayMemory0.byteLength === 0) {
    cachedUint32ArrayMemory0 = new Uint32Array(wasm.memory.buffer);
  }
  return cachedUint32ArrayMemory0;
}

let cachedUint8ArrayMemory0 = null;
function getUint8ArrayMemory0() {
  if (cachedUint8ArrayMemory0 === null || cachedUint8ArrayMemory0.byteLength === 0) {
    cachedUint8ArrayMemory0 = new Uint8Array(wasm.memory.buffer);
  }
  return cachedUint8ArrayMemory0;
}

function getObject(idx) {
  return heap[idx];
}

function handleError(f, args) {
  try {
    return f.apply(this, args);
  } catch (e) {
    wasm.__wbindgen_export3(addHeapObject(e));
  }
}

let heap = new Array(1024).fill(undefined);
heap.push(undefined, null, true, false);

let heap_next = heap.length;

function isLikeNone(x) {
  return x === undefined || x === null;
}

function passArray32ToWasm0(arg, malloc) {
  const ptr = malloc(arg.length * 4, 4) >>> 0;
  getUint32ArrayMemory0().set(arg, ptr / 4);
  WASM_VECTOR_LEN = arg.length;
  return ptr;
}

function passArray8ToWasm0(arg, malloc) {
  const ptr = malloc(arg.length * 1, 1) >>> 0;
  getUint8ArrayMemory0().set(arg, ptr / 1);
  WASM_VECTOR_LEN = arg.length;
  return ptr;
}

function passArrayJsValueToWasm0(array, malloc) {
  const ptr = malloc(array.length * 4, 4) >>> 0;
  const mem = getDataViewMemory0();
  for (let i = 0; i < array.length; i++) {
    mem.setUint32(ptr + 4 * i, addHeapObject(array[i]), true);
  }
  WASM_VECTOR_LEN = array.length;
  return ptr;
}

function passStringToWasm0(arg, malloc, realloc) {
  if (realloc === undefined) {
    const buf = cachedTextEncoder.encode(arg);
    const ptr = malloc(buf.length, 1) >>> 0;
    getUint8ArrayMemory0()
      .subarray(ptr, ptr + buf.length)
      .set(buf);
    WASM_VECTOR_LEN = buf.length;
    return ptr;
  }

  let len = arg.length;
  let ptr = malloc(len, 1) >>> 0;

  const mem = getUint8ArrayMemory0();

  let offset = 0;

  for (; offset < len; offset++) {
    const code = arg.charCodeAt(offset);
    if (code > 0x7f) break;
    mem[ptr + offset] = code;
  }
  if (offset !== len) {
    if (offset !== 0) {
      arg = arg.slice(offset);
    }
    ptr = realloc(ptr, len, (len = offset + arg.length * 3), 1) >>> 0;
    const view = getUint8ArrayMemory0().subarray(ptr + offset, ptr + len);
    const ret = cachedTextEncoder.encodeInto(arg, view);

    offset += ret.written;
    ptr = realloc(ptr, len, offset, 1) >>> 0;
  }

  WASM_VECTOR_LEN = offset;
  return ptr;
}

let stack_pointer = 1024;

function takeObject(idx) {
  const ret = getObject(idx);
  dropObject(idx);
  return ret;
}

let cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
cachedTextDecoder.decode();
const MAX_SAFARI_DECODE_BYTES = 2146435072;
let numBytesDecoded = 0;
function decodeText(ptr, len) {
  numBytesDecoded += len;
  if (numBytesDecoded >= MAX_SAFARI_DECODE_BYTES) {
    cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
    cachedTextDecoder.decode();
    numBytesDecoded = len;
  }
  return cachedTextDecoder.decode(getUint8ArrayMemory0().subarray(ptr, ptr + len));
}

const cachedTextEncoder = new TextEncoder();

if (!('encodeInto' in cachedTextEncoder)) {
  cachedTextEncoder.encodeInto = function (arg, view) {
    const buf = cachedTextEncoder.encode(arg);
    view.set(buf);
    return {
      read: arg.length,
      written: buf.length,
    };
  };
}

let WASM_VECTOR_LEN = 0;

let wasmModule, wasmInstance, wasm;
function __wbg_finalize_init(instance, module) {
  wasmInstance = instance;
  wasm = instance.exports;
  wasmModule = module;
  cachedDataViewMemory0 = null;
  cachedFloat64ArrayMemory0 = null;
  cachedUint32ArrayMemory0 = null;
  cachedUint8ArrayMemory0 = null;
  wasm.__wbindgen_start();
  return wasm;
}

async function __wbg_load(module, imports) {
  if (typeof Response === 'function' && module instanceof Response) {
    if (typeof WebAssembly.instantiateStreaming === 'function') {
      try {
        return await WebAssembly.instantiateStreaming(module, imports);
      } catch (e) {
        const validResponse = module.ok && expectedResponseType(module.type);

        if (validResponse && module.headers.get('Content-Type') !== 'application/wasm') {
          console.warn(
            '`WebAssembly.instantiateStreaming` failed because your server does not serve Wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:\n',
            e,
          );
        } else {
          throw e;
        }
      }
    }

    const bytes = await module.arrayBuffer();
    return await WebAssembly.instantiate(bytes, imports);
  } else {
    const instance = await WebAssembly.instantiate(module, imports);

    if (instance instanceof WebAssembly.Instance) {
      return { instance, module };
    } else {
      return instance;
    }
  }

  function expectedResponseType(type) {
    switch (type) {
      case 'basic':
      case 'cors':
      case 'default':
        return true;
    }
    return false;
  }
}

function initSync(module) {
  if (wasm !== undefined) return wasm;

  if (module !== undefined) {
    if (Object.getPrototypeOf(module) === Object.prototype) {
      ({ module } = module);
    } else {
      console.warn('using deprecated parameters for `initSync()`; pass a single object instead');
    }
  }

  const imports = __wbg_get_imports();
  if (!(module instanceof WebAssembly.Module)) {
    module = new WebAssembly.Module(module);
  }
  const instance = new WebAssembly.Instance(module, imports);
  return __wbg_finalize_init(instance, module);
}

async function __wbg_init(module_or_path) {
  if (wasm !== undefined) return wasm;

  if (module_or_path !== undefined) {
    if (Object.getPrototypeOf(module_or_path) === Object.prototype) {
      ({ module_or_path } = module_or_path);
    } else {
      console.warn('using deprecated parameters for the initialization function; pass a single object instead');
    }
  }

  if (module_or_path === undefined) {
    module_or_path = new URL('engine_wasm_bg.wasm', import.meta.url);
  }
  const imports = __wbg_get_imports();

  if (
    typeof module_or_path === 'string' ||
    (typeof Request === 'function' && module_or_path instanceof Request) ||
    (typeof URL === 'function' && module_or_path instanceof URL)
  ) {
    module_or_path = fetch(module_or_path);
  }

  const { instance, module } = await __wbg_load(await module_or_path, imports);

  return __wbg_finalize_init(instance, module);
}

export { initSync, __wbg_init as default };
