/// <reference lib="webworker" />
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * PDFium render worker (Phase 1 harness).
 *
 * Runs PDFium entirely off the main thread. Because PDFium rasterizes glyph
 * outlines itself (no DOM `FontFace`), text renders correctly here — the exact
 * thing pd​f.js could not do in a worker.
 *
 * Bootstrap (per pdfium-render's WASM contract — see PDFIUM_ENGINE.md §9a):
 *   1. Load the vendored **emscripten** PDFium module (`pdfium.js` → `pdfium.wasm`).
 *   2. Init our `pdf_engine` wasm-bindgen glue.
 *   3. Call `initialize_pdfium_render(pdfiumModule, ourModule, debug)` to wire
 *      PDFium's C functions into the Rust bindings.
 *
 * ⚠️ TWO inputs are still required before this runs (neither is in the repo yet):
 *   - the emscripten `pdfium.wasm` + `pdfium.js` (vendor from
 *     paulocoutinhox/pdfium-lib — the native `.so/.dylib/.dll` in
 *     external/pdfium/runtimes/ are NOT usable in a browser);
 *   - the built `pdf_engine` glue (`npm run build:wasm` → src/lib/wasm/pdf/).
 * This worker is built by a dedicated esbuild step (like the old render
 * worker), NOT by ng-packagr.
 */

// NOTE: paths resolve once `npm run build:wasm` emits the pdf_engine glue and
// the MODULARIZE/EXPORT_ES6 pdfium build is vendored into src/lib/wasm/pdfium/.
// Kept as static imports so the dedicated worker build bundles them; ng-packagr
// ignores this file (`**/*.worker.ts`).
// prettier-ignore
// @ts-expect-error — generated by `npm run build:wasm`; absent until then.
import initPdfEngine, { initialize_pdfium_render, open, close, page_count, page_size, document_title, render, page_text, outline, page_links, document_annotations, attachments, form_fields, set_field_value, add_highlight, add_text_note, add_free_text, add_ink, delete_annotation, set_annotation_contents, delete_page, insert_blank_page, set_page_rotation, save_document } from '../../../wasm/pdf/pdf_engine.js';
// @ts-expect-error — vendored emscripten MODULARIZE+EXPORT_ES6 build; absent until then.
import createPdfiumModule from './pdfium/pdfium.js';
// Both .wasm are embedded into the worker bundle by esbuild's `binary` loader
// (scripts/build-pdfium-worker.mjs) → zero fetches, zero consumer setup. They
// arrive here as Uint8Array. pd_engine glue lives under wasm/pdf/ (regenerated
// by `npm run engine:build`); the vendored pdfium lives under engine/pdfium/.
// @ts-expect-error — esbuild binary loader; resolved by the worker build.
import pdfEngineWasm from '../../../wasm/pdf/pdf_engine_bg.wasm';
// @ts-expect-error — esbuild binary loader; resolved by the worker build.
import pdfiumWasm from './pdfium/pdfium.wasm';

import type { PdfWorkerRequest } from './pdf-engine.types';

const ctx = self as unknown as Worker;

/**
 * Load the emscripten PDFium module. The exact entry depends on the vendored
 * build (paulocoutinhox ships an emscripten factory). Replace the import +
 * factory call to match the vendored artifact, returning the initialized
 * `Module` object that `initialize_pdfium_render` expects.
 */
function loadPdfiumModule(): Promise<any> {
  // Emscripten MODULARIZE + EXPORT_ES6: default export is a factory →
  // Promise<Module>. `wasmBinary` feeds the embedded bytes directly so the
  // module never fetches anything (fully self-contained / zero consumer setup).
  //
  // `locateFile` MUST be provided even though we supply the bytes: emscripten's
  // `findWasmBinary()` otherwise falls back to `new URL("pdfium.esm.wasm",
  // import.meta.url)`, and in a Blob-URL module worker `import.meta.url` is an
  // opaque `blob:` URL that can't be a base → "Failed to construct 'URL'". With
  // `locateFile` set, that branch returns the (unused) path string instead.
  return createPdfiumModule({
    wasmBinary: pdfiumWasm,
    locateFile: (path: string) => path,
  });
}

let ready: Promise<void> | null = null;
function bootstrap(): Promise<void> {
  if (ready) return ready;
  ready = (async () => {
    const [pdfiumModule, ourModule] = await Promise.all([
      loadPdfiumModule(),
      // wasm-bindgen (--target web) init: pass the embedded bytes via the
      // modern `{ module_or_path }` form (a bare Uint8Array also works but logs
      // a deprecation warning).
      initPdfEngine({ module_or_path: pdfEngineWasm }),
    ]);
    const ok = initialize_pdfium_render(pdfiumModule, ourModule, false);
    if (!ok) throw new Error('initialize_pdfium_render failed');
  })();
  return ready;
}

// The document handle is the Rust-side registry key — PDFium parses the bytes
// once in `open` and keeps the `PdfDocument` alive, so `render`/`page_text`/
// `page_size` reuse it with no re-parse. No bytes are retained on the JS side.

ctx.onmessage = async (e: MessageEvent<PdfWorkerRequest>) => {
  const msg = e.data;
  try {
    await bootstrap();
    switch (msg.type) {
      case 'open': {
        const handle = open(new Uint8Array(msg.bytes), msg.password) as number;
        ctx.postMessage({ type: 'ok', id: msg.id, result: handle });
        break;
      }
      case 'pageCount': {
        const count = page_count(msg.doc) as number;
        ctx.postMessage({ type: 'ok', id: msg.id, result: count });
        break;
      }
      case 'pageSize': {
        const [w, h] = page_size(msg.doc, msg.page) as unknown as [number, number];
        ctx.postMessage({ type: 'ok', id: msg.id, result: { width: w, height: h } });
        break;
      }
      case 'documentTitle': {
        ctx.postMessage({ type: 'ok', id: msg.id, result: document_title(msg.doc) as string });
        break;
      }
      case 'render': {
        // Clamp to [1, 8192]. 8192 is the GPU/canvas max-texture ceiling and is
        // far above any legitimate fit-* render (~2-3k px); the upper bound is
        // purely defensive so a pathological size can never OOM PDFium's bitmap
        // allocator (which surfaces as PdfiumLibraryInternalError(Unknown)).
        const MAX_RENDER_WIDTH = 8192;
        const requested = Math.floor(msg.cssWidth * msg.dpr);
        const targetWidth = Math.max(1, Math.min(MAX_RENDER_WIDTH, requested));
        if (requested > MAX_RENDER_WIDTH) {
          console.warn(`[hk-pdf-viewer] render width ${requested}px clamped to ${MAX_RENDER_WIDTH}px`);
        }
        const [width, height, rgba] = render(msg.doc, msg.page, targetWidth) as unknown as [number, number, Uint8Array];
        const image = new ImageData(new Uint8ClampedArray(rgba), width, height);
        const bitmap = await createImageBitmap(image);
        ctx.postMessage({ type: 'rendered', id: msg.id, bitmap, width, height }, [bitmap]);
        break;
      }
      case 'pageText': {
        // Each row is [text, x, y, w, h]; map to PdfTextSegment objects.
        const rows = page_text(msg.doc, msg.page) as unknown as Array<[string, number, number, number, number]>;
        const segments = rows.map(([text, x, y, w, h]) => ({ text, x, y, w, h }));
        ctx.postMessage({ type: 'ok', id: msg.id, result: segments });
        break;
      }
      case 'outline': {
        // Recursive [title, pageIndex, children[]] → PdfOutlineNode.
        type Row = [string, number, Row[]];
        const toNode = (r: Row): unknown => ({ title: r[0], pageIndex: r[1], children: (r[2] ?? []).map(toNode) });
        const tree = (outline(msg.doc) as unknown as Row[]).map(toNode);
        ctx.postMessage({ type: 'ok', id: msg.id, result: tree });
        break;
      }
      case 'pageLinks': {
        const rows = page_links(msg.doc, msg.page) as unknown as Array<[number, number, number, number, number, string]>;
        const links = rows.map(([x, y, w, h, pageIndex, uri]) => ({ x, y, w, h, pageIndex, uri }));
        ctx.postMessage({ type: 'ok', id: msg.id, result: links });
        break;
      }
      case 'documentAnnotations': {
        const rows = document_annotations(msg.doc) as unknown as Array<[number, number, string, string]>;
        const list = rows.map(([pageIndex, index, subtype, contents]) => ({ pageIndex, index, subtype, contents }));
        ctx.postMessage({ type: 'ok', id: msg.id, result: list });
        break;
      }
      case 'attachments': {
        const rows = attachments(msg.doc) as unknown as Array<[string, Uint8Array]>;
        const list = rows.map(([name, bytes]) => ({ name, bytes }));
        ctx.postMessage({ type: 'ok', id: msg.id, result: list });
        break;
      }
      case 'formFields': {
        // Each row is [name, type, x, y, w, h, value, readOnly, checked, options].
        const rows = form_fields(msg.doc, msg.page) as unknown as Array<
          [string, string, number, number, number, number, string, number, number, string[]]
        >;
        const fields = rows.map(([name, type, x, y, w, h, value, readOnly, checked, options]) => ({
          name,
          type,
          x,
          y,
          w,
          h,
          value,
          readOnly: readOnly === 1,
          checked: checked === 1,
          options,
        }));
        ctx.postMessage({ type: 'ok', id: msg.id, result: fields });
        break;
      }
      case 'setFieldValue': {
        const ok = set_field_value(msg.doc, msg.page, msg.name, msg.value) as boolean;
        ctx.postMessage({ type: 'ok', id: msg.id, result: ok });
        break;
      }
      case 'addHighlight': {
        const ok = add_highlight(msg.doc, msg.page, msg.x, msg.y, msg.w, msg.h, msg.color >>> 0) as boolean;
        ctx.postMessage({ type: 'ok', id: msg.id, result: ok });
        break;
      }
      case 'addTextNote': {
        const ok = add_text_note(msg.doc, msg.page, msg.x, msg.y, msg.contents, msg.color >>> 0) as boolean;
        ctx.postMessage({ type: 'ok', id: msg.id, result: ok });
        break;
      }
      case 'addFreeText': {
        const ok = add_free_text(msg.doc, msg.page, msg.x, msg.y, msg.w, msg.h, msg.contents, msg.color >>> 0) as boolean;
        ctx.postMessage({ type: 'ok', id: msg.id, result: ok });
        break;
      }
      case 'addInk': {
        const ok = add_ink(msg.doc, msg.page, Float32Array.from(msg.points), msg.color >>> 0, msg.width) as boolean;
        ctx.postMessage({ type: 'ok', id: msg.id, result: ok });
        break;
      }
      case 'deleteAnnotation': {
        const ok = delete_annotation(msg.doc, msg.page, msg.index) as boolean;
        ctx.postMessage({ type: 'ok', id: msg.id, result: ok });
        break;
      }
      case 'setAnnotationContents': {
        const ok = set_annotation_contents(msg.doc, msg.page, msg.index, msg.contents) as boolean;
        ctx.postMessage({ type: 'ok', id: msg.id, result: ok });
        break;
      }
      case 'deletePage': {
        const ok = delete_page(msg.doc, msg.index) as boolean;
        ctx.postMessage({ type: 'ok', id: msg.id, result: ok });
        break;
      }
      case 'insertBlankPage': {
        const ok = insert_blank_page(msg.doc, msg.index, msg.width, msg.height) as boolean;
        ctx.postMessage({ type: 'ok', id: msg.id, result: ok });
        break;
      }
      case 'setPageRotation': {
        const ok = set_page_rotation(msg.doc, msg.page, msg.degrees) as boolean;
        ctx.postMessage({ type: 'ok', id: msg.id, result: ok });
        break;
      }
      case 'save': {
        const bytes = save_document(msg.doc) as Uint8Array;
        // Transfer the underlying buffer so the bytes don't get copied again.
        ctx.postMessage({ type: 'ok', id: msg.id, result: bytes }, [bytes.buffer]);
        break;
      }
      case 'dispose':
        close(msg.doc);
        break;
    }
  } catch (err) {
    if ('id' in msg) ctx.postMessage({ type: 'error', id: (msg as { id: number }).id, message: String((err as Error)?.message ?? err) });
  }
};
