#!/usr/bin/env node
/**
 * Build the hakistack engine WASM bundles and place their output where the
 * Angular library can lazy-load them.
 *
 * Two bundles, two output folders:
 *
 *   1. engine_wasm    — table / tree / fuzzy / form / pdf-search kernels.
 *                       Loaded by `<hk-table>`, `<hk-tree>`, command-palette,
 *                       select, dynamic-form, pdf-viewer.
 *   2. document_wasm  — calamine-backed spreadsheet parsing (later: docx,
 *                       pptx, doc/ppt/xls binary). Loaded only by
 *                       `<hk-document-viewer>`.
 *
 * Each bundle is wasm-packed, copied to its own subfolder under
 * `projects/hakistack/ng-daisyui/src/lib/wasm/`, and emitted alongside a
 * `*_glue.ts` + `*_inline.ts` pair so ng-packagr bundles both into the FESM.
 * The dynamic-import in each loader gives bundlers a tree-shaking seam, so
 * apps that don't touch a particular bundle don't pay for its base64.
 *
 * Requires `wasm-pack` on PATH:  `cargo install wasm-pack`
 */

import { execSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE   = dirname(fileURLToPath(import.meta.url));
const ROOT   = resolve(HERE, '..');
const ENGINE = resolve(ROOT, 'hakistack-engine');

const profile = process.argv.includes('--dev') ? '--dev' : '--release';

try {
  execSync('wasm-pack --version', { stdio: 'ignore' });
} catch {
  console.error(
    'wasm-pack not found.\n' +
    '  Install with:  cargo install wasm-pack\n' +
    '  or:            curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh',
  );
  process.exit(1);
}

/**
 * Build, copy, and inline a single wasm-pack crate.
 *
 * @param {Object} cfg
 * @param {string} cfg.cratePath     — path under hakistack-engine/crates
 * @param {string} cfg.pkgDirName    — output folder name under hakistack-engine/<this>
 * @param {string} cfg.bundleName    — base file name (e.g. 'engine_wasm')
 * @param {string} cfg.libSubdir     — destination folder under .../lib/wasm/
 * @param {Array<string>} cfg.publicTargets — optional dev-only copies (.js + .wasm)
 */
function buildBundle({ cratePath, pkgDirName, bundleName, libSubdir, publicTargets = [] }) {
  const PKG = resolve(ENGINE, pkgDirName);

  // Release builds drop `console_error_panic_hook` (saves ~5 KB) — wasm-pack
  // understands `--no-default-features` to mean "skip the `default` feature
  // set," which for both umbrellas is just the `debug-panics` feature.
  const featureFlags = profile === '--release' ? '--no-default-features' : '';

  console.log(`▶ wasm-pack build ${cratePath}  (${profile}${featureFlags ? ` ${featureFlags}` : ''})`);
  execSync(
    `wasm-pack build ${cratePath} --target web --out-dir ../../${pkgDirName} ${profile} ${featureFlags}`.trim(),
    { stdio: 'inherit', cwd: ENGINE },
  );

  const libTarget = resolve(ROOT, 'projects/hakistack/ng-daisyui/src/lib/wasm', libSubdir);

  // Lib copy: replace the whole folder so stale files don't linger.
  if (existsSync(libTarget)) rmSync(libTarget, { recursive: true, force: true });
  mkdirSync(libTarget, { recursive: true });
  cpSync(PKG, libTarget, { recursive: true });
  console.log(`✓ ${libTarget.replace(ROOT + '/', '')}`);

  // ─── Inline-bundle generation ───────────────────────────────────────────
  //
  // ng-packagr only bundles `.ts` files reachable from the entry point. To
  // ship the bundle inside the FESM (so consumers don't have to copy WASM
  // to their public/ folder), we emit two siblings of the wasm-pack output:
  //
  //   - <bundleName>_glue.ts   = <bundleName>.js + `// @ts-nocheck` header
  //   - <bundleName>_inline.ts = `export const <UPPER>_BASE64 = '...';`
  //
  // The matching loader dynamic-imports both, decodes the base64 →
  // Uint8Array, and passes it to the glue's `default()` initializer.
  const glueJsPath = resolve(libTarget, `${bundleName}.js`);
  const wasmPath = resolve(libTarget, `${bundleName}_bg.wasm`);

  const glueJs = readFileSync(glueJsPath, 'utf8');
  // The wasm-pack glue is plain ES; TS strict mode chokes on the dynamically
  // typed `wasm` variable. `@ts-nocheck` keeps ng-packagr happy without
  // editing the generated file's logic.
  const glueTs = `// @ts-nocheck\n/* eslint-disable */\n// Auto-generated by scripts/build-wasm.mjs from ${bundleName}.js. Do not edit.\n${glueJs}`;
  writeFileSync(resolve(libTarget, `${bundleName}_glue.ts`), glueTs);

  const wasmBytes = readFileSync(wasmPath);
  const wasmBase64 = wasmBytes.toString('base64');
  const constName = `${bundleName.toUpperCase()}_BASE64`;
  const inlineTs =
    `// Auto-generated by scripts/build-wasm.mjs. Do not edit.\n` +
    `// Base64 of ${bundleName}_bg.wasm (${wasmBytes.length.toLocaleString()} raw bytes).\n` +
    `export const ${constName} = ${JSON.stringify(wasmBase64)};\n`;
  writeFileSync(resolve(libTarget, `${bundleName}_inline.ts`), inlineTs);

  const kb = (n) => `${(n / 1024).toFixed(1)} KB`;
  console.log(`✓ ${libTarget.replace(ROOT + '/', '')}/${bundleName}_glue.ts (${kb(glueTs.length)})`);
  console.log(`✓ ${libTarget.replace(ROOT + '/', '')}/${bundleName}_inline.ts (base64 ${kb(wasmBase64.length)} from ${kb(wasmBytes.length)} raw)`);

  // Demo copies: only the .js + .wasm files. Don't overwrite an entire shared
  // assets/ folder since other files live there.
  const wasmFiles = [`${bundleName}.js`, `${bundleName}_bg.wasm`];
  for (const target of publicTargets) {
    if (!existsSync(target)) continue; // demo project absent in this checkout — skip silently
    for (const f of wasmFiles) {
      cpSync(resolve(PKG, f), resolve(target, f));
    }
    console.log(`✓ ${target.replace(ROOT + '/', '')} (${bundleName}.{js,wasm})`);
  }
}

// ─── engine_wasm bundle (table / tree / fuzzy / form / pdf-search) ──────────
buildBundle({
  cratePath:     'crates/engine-wasm',
  pkgDirName:    'pkg',
  bundleName:    'engine_wasm',
  libSubdir:     '.',
  publicTargets: [
    resolve(ROOT, 'projects/demo/public'),
    resolve(ROOT, 'projects/demo-v4/public'),
  ],
});

// ─── document_wasm bundle (calamine — spreadsheets) ─────────────────────────
buildBundle({
  cratePath:     'crates/document-wasm',
  pkgDirName:    'pkg-document',
  bundleName:    'document_wasm',
  libSubdir:     'document',
  publicTargets: [
    resolve(ROOT, 'projects/demo/public'),
    resolve(ROOT, 'projects/demo-v4/public'),
  ],
});

// ─── image_wasm bundle (Rust `image` crate — TIFF + minor formats) ──────────
buildBundle({
  cratePath:     'crates/image-wasm',
  pkgDirName:    'pkg-image',
  bundleName:    'image_wasm',
  libSubdir:     'image',
  publicTargets: [
    resolve(ROOT, 'projects/demo/public'),
    resolve(ROOT, 'projects/demo-v4/public'),
  ],
});

// ─── pdf_engine bundle (pdfium-render bindings — the PDFium PDF engine) ──────
// This emits the *bindings* glue only; the actual PDFium engine ships as a
// separate vendored `pdfium.wasm` loaded at runtime (paulocoutinhox/pdfium-lib,
// growable heap). See PDFIUM_ENGINE.md. Built by the pipeline now; the loader/
// worker that import it land in Phase 1 (until then it's tree-shaken out).
buildBundle({
  cratePath:     'crates/pdf-engine',
  pkgDirName:    'pkg-pdf',
  bundleName:    'pdf_engine',
  libSubdir:     'pdf',
  publicTargets: [
    resolve(ROOT, 'projects/demo/public'),
    resolve(ROOT, 'projects/demo-v4/public'),
  ],
});
