#!/usr/bin/env node
/**
 * Build hakistack-engine and place its output where the Angular library can lazy-load it.
 *
 *   1. `wasm-pack build crates/engine-wasm --target web --out-dir ../../pkg`
 *   2. copy hakistack-engine/pkg → projects/hakistack/ng-daisyui/src/lib/wasm
 *
 * Requires `wasm-pack` on PATH:  `cargo install wasm-pack`
 */

import { execSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE   = dirname(fileURLToPath(import.meta.url));
const ROOT   = resolve(HERE, '..');
const ENGINE = resolve(ROOT, 'hakistack-engine');
const PKG    = resolve(ENGINE, 'pkg');

// Where the WASM bundle gets copied. Order matters: lib/wasm holds the
// canonical copy that ships in the published package; demo/public are dev
// conveniences so `ng serve` can find /engine_wasm.js.
const COPY_TARGETS = [
  resolve(ROOT, 'projects/hakistack/ng-daisyui/src/lib/wasm'),
  resolve(ROOT, 'projects/demo/public'),
  resolve(ROOT, 'projects/demo-v4/public'),
];

const profile = process.argv.includes('--dev') ? '--dev' : '--release';

try {
  execSync('wasm-pack --version', { stdio: 'ignore' });
} catch {
  console.error(
    'wasm-pack not found.\n' +
    '  Install with:  cargo install wasm-pack\n' +
    '  or:            curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh',
  );
  process.exit(1);
}

// Release builds drop `console_error_panic_hook` (saves ~5 KB) — wasm-pack
// understands `--no-default-features` to mean "skip the `default` feature
// set," which for engine-wasm is just the `debug-panics` feature.
const featureFlags = profile === '--release' ? '--no-default-features' : '';

console.log(`▶ wasm-pack build  (${profile}${featureFlags ? ` ${featureFlags}` : ''})`);
execSync(
  `wasm-pack build crates/engine-wasm --target web --out-dir ../../pkg ${profile} ${featureFlags}`.trim(),
  { stdio: 'inherit', cwd: ENGINE },
);

// Lib copy: replace the whole folder so stale files don't linger.
const libTarget = COPY_TARGETS[0];
if (existsSync(libTarget)) rmSync(libTarget, { recursive: true, force: true });
mkdirSync(libTarget, { recursive: true });
cpSync(PKG, libTarget, { recursive: true });
console.log(`✓ ${libTarget.replace(ROOT + '/', '')}`);

// ─── Inline-bundle generation ─────────────────────────────────────────────
//
// ng-packagr only bundles `.ts` files reachable from the entry point. To
// ship the engine inside the FESM (so consumers don't have to copy WASM to
// their public/ folder), we emit two siblings of the wasm-pack output:
//
//   - engine_wasm_glue.ts   = engine_wasm.js + `// @ts-nocheck` header
//   - engine_wasm_inline.ts = `export const ENGINE_WASM_BASE64 = '...';`
//
// The shared loader (lib/components/table/engine/engine-loader.ts) dynamic-
// imports both, decodes the base64 → Uint8Array, and passes it to the
// glue's `default()` initializer — no fetch, no URL config.
{
  const glueJsPath = resolve(libTarget, 'engine_wasm.js');
  const wasmPath = resolve(libTarget, 'engine_wasm_bg.wasm');

  const glueJs = readFileSync(glueJsPath, 'utf8');
  // The wasm-pack glue is plain ES; TS strict mode chokes on the dynamically
  // typed `wasm` variable. `@ts-nocheck` keeps ng-packagr happy without
  // editing the generated file's logic.
  const glueTs = `// @ts-nocheck\n/* eslint-disable */\n// Auto-generated by scripts/build-wasm.mjs from engine_wasm.js. Do not edit.\n${glueJs}`;
  writeFileSync(resolve(libTarget, 'engine_wasm_glue.ts'), glueTs);

  const wasmBytes = readFileSync(wasmPath);
  const wasmBase64 = wasmBytes.toString('base64');
  const inlineTs =
    `// Auto-generated by scripts/build-wasm.mjs. Do not edit.\n` +
    `// Base64 of engine_wasm_bg.wasm (${wasmBytes.length.toLocaleString()} raw bytes).\n` +
    `export const ENGINE_WASM_BASE64 = ${JSON.stringify(wasmBase64)};\n`;
  writeFileSync(resolve(libTarget, 'engine_wasm_inline.ts'), inlineTs);

  const kb = (n) => `${(n / 1024).toFixed(1)} KB`;
  console.log(`✓ ${libTarget.replace(ROOT + '/', '')}/engine_wasm_glue.ts (${kb(glueTs.length)})`);
  console.log(`✓ ${libTarget.replace(ROOT + '/', '')}/engine_wasm_inline.ts (base64 ${kb(wasmBase64.length)} from ${kb(wasmBytes.length)} raw)`);
}

// Demo copies: only the .js + .wasm files. Don't overwrite an entire shared
// assets/ folder since other files live there.
const wasmFiles = ['engine_wasm.js', 'engine_wasm_bg.wasm'];
for (const target of COPY_TARGETS.slice(1)) {
  if (!existsSync(target)) {
    // Demo project not present in this checkout — skip silently.
    continue;
  }
  for (const f of wasmFiles) {
    cpSync(resolve(PKG, f), resolve(target, f));
  }
  console.log(`✓ ${target.replace(ROOT + '/', '')} (engine_wasm.{js,wasm})`);
}
