// AUTO-GENERATED by scripts/extract-api-docs.mjs — DO NOT EDIT BY HAND.
// Re-run `npm run extract-api-docs` after changing component inputs / outputs.

export interface ApiInputEntry {
  readonly name: string;
  readonly type: string;
  readonly default?: string;
  readonly description: string;
}

export interface ApiOutputEntry {
  readonly name: string;
  readonly type: string;
  readonly description: string;
}

export interface ComponentApi {
  readonly className: string;
  readonly selector: string;
  readonly description: string;
  readonly inputs: readonly ApiInputEntry[];
  readonly outputs: readonly ApiOutputEntry[];
}

// Pattern: keep literal-typed keys for the ApiComponentName union, but
// widen the entry type so consumers can read optional fields like
// inputs[i].default uniformly without TS narrowing them away on items
// where the key happens to be absent in the literal.
const _API_DOCS = {
  AlertOverlayComponent: {
    className: 'AlertOverlayComponent',
    selector: 'hk-alert-overlay',
    description: '',
    inputs: [
      {
        name: 'config',
        type: 'AlertInternalConfig',
        description: '',
      },
    ],
    outputs: [],
  },
  CommandPaletteComponent: {
    className: 'CommandPaletteComponent',
    selector: 'hk-command-palette',
    description:
      'Modal command palette — a search-driven launcher with grouped results, mode prefixes, and a global hotkey. Native to the lib (no `@tailwindplus/elements` runtime, no commercial license). Configuration is **builder-only** (matching `createForm` / `createTable` / `createPdfViewer`). Pass `controller.config()` from a `createCommandPalette({...})` call to `[config]`. Imperative actions (`open` / `close` / `toggle` / `setQuery` / `clear`) live on the controller — no `@ViewChild` needed.',
    inputs: [
      {
        name: 'config',
        type: 'CommandPaletteConfig',
        description: 'Configuration object — pass `controller.config()` from a `createCommandPalette({...})` call.',
      },
    ],
    outputs: [],
  },
  DatepickerComponent: {
    className: 'DatepickerComponent',
    selector: 'hk-datepicker',
    description: '',
    inputs: [
      {
        name: 'range',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'showTime',
        type: 'boolean',
        default: 'false',
        description: 'Show time selection panel alongside the calendar',
      },
      {
        name: 'use24Hour',
        type: 'boolean',
        default: 'false',
        description: 'Use 24-hour format for time display (default: false = 12-hour with AM/PM)',
      },
      {
        name: 'minuteStep',
        type: 'number',
        default: '1',
        description: 'Minute step interval (default: 1)',
      },
      {
        name: 'placeholder',
        type: 'string',
        default: "'Select Date'",
        description: '',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'locale',
        type: 'string',
        default: "'en-US'",
        description: '',
      },
      {
        name: 'labels',
        type: 'DatepickerLabels',
        default: '{}',
        description: 'Text overrides for every visible string in the dropdown. See `DatepickerLabels`.',
      },
      {
        name: 'minDate',
        type: 'Date | undefined',
        description: '',
      },
      {
        name: 'maxDate',
        type: 'Date | undefined',
        description: '',
      },
      {
        name: 'disabledDates',
        type: 'Date[]',
        default: '[]',
        description: '',
      },
      {
        name: 'disabledDaysOfWeek',
        type: 'number[]',
        default: '[]',
        description: '',
      },
      {
        name: 'showWeekNumbers',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'firstDayOfWeek',
        type: 'number',
        default: '0',
        description: '',
      },
      {
        name: 'closeOnSelect',
        type: 'boolean',
        default: 'this.defaultConfig.closeOnSelect!',
        description: '',
      },
      {
        name: 'showClearButton',
        type: 'boolean',
        default: 'this.defaultConfig.showClearButton!',
        description: '',
      },
      {
        name: 'showTodayButton',
        type: 'boolean',
        default: 'this.defaultConfig.showTodayButton!',
        description: '',
      },
      {
        name: 'dropdownPosition',
        type: 'DatepickerPosition',
        default: "'bottom-left'",
        description: '',
      },
      {
        name: 'minWidth',
        type: 'string',
        default: "'20rem'",
        description: '',
      },
      {
        name: 'required',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'name',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'formControlName',
        type: 'string',
        default: "''",
        description: '',
      },
    ],
    outputs: [
      {
        name: 'selectionChange',
        type: 'DatepickerEvent',
        description: '',
      },
      {
        name: 'dateSelected',
        type: 'Date',
        description: '',
      },
      {
        name: 'rangeSelected',
        type: '{ start: Date; end: Date }',
        description: '',
      },
      {
        name: 'pickerOpened',
        type: 'void',
        description: '',
      },
      {
        name: 'pickerClosed',
        type: 'void',
        description: '',
      },
      {
        name: 'viewChanged',
        type: 'ViewMode',
        description: '',
      },
    ],
  },
  DynamicFormComponent: {
    className: 'DynamicFormComponent',
    selector: 'hk-dynamic-form',
    description: '',
    inputs: [
      {
        name: 'config',
        type: 'FormConfig',
        description: '',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        description: '',
      },
    ],
    outputs: [
      {
        name: 'formSubmit',
        type: 'FormSubmissionData',
        description: '',
      },
      {
        name: 'formReset',
        type: 'void',
        description: '',
      },
      {
        name: 'stepChange',
        type: 'StepChangeEvent',
        description: '',
      },
    ],
  },
  EditorComponent: {
    className: 'EditorComponent',
    selector: 'hk-editor',
    description:
      "Rich text editor — TipTap (ProseMirror) backed, DaisyUI-native. Architecture: - This component owns the editor lifecycle, CVA, validation, commands. - `<hk-editor-toolbar>` (separate component) renders the toolbar chrome. - `ViewEncapsulation.None` + `.hk-editor__*` BEM prefix: TipTap injects its `.ProseMirror` DOM dynamically, which Angular's emulated encapsulation never reaches. Unscoped styles under a unique prefix give us theming without leaking globally. Value contract: HTML string via `ControlValueAccessor`. Engine lazy-loaded in `afterNextRender`.",
    inputs: [
      {
        name: 'placeholder',
        type: 'string',
        default: "'Write something…'",
        description: '',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'readonly',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'toolbar',
        type: 'EditorToolbarConfig',
        default: "'basic'",
        description: '',
      },
      {
        name: 'minLength',
        type: 'number | null',
        default: 'null',
        description: '',
      },
      {
        name: 'maxLength',
        type: 'number | null',
        default: 'null',
        description: '',
      },
      {
        name: 'editorHeight',
        type: 'string',
        default: "'200px'",
        description: '',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'contentClass',
        type: 'string',
        default: "''",
        description:
          "Extra class names applied to the editor's content root (TipTap's `.tiptap` element) via the documented `editorProps.attributes.class` API. Handy for adding typography utilities like `prose prose-sm` without overriding our built-in styling. Read once at init — static by design.",
      },
      {
        name: 'onImageUpload',
        type: 'EditorImageUploader | undefined',
        default: 'undefined',
        description:
          'Async callback invoked when the Image toolbar button is clicked and the user picks a file. Return the URL to insert. If not provided, the Image button falls back to a URL prompt. Storage is consumer-owned.',
      },
      {
        name: 'slashCommands',
        type: 'EditorSlashCommandConfig',
        default: 'false',
        description:
          "Notion-style slash-command popup. `false` (default) disables the feature. `true` enables the built-in command set. An array replaces the built-ins with the consumer's own list. `{ items, append: true }` extends built-ins.",
      },
    ],
    outputs: [
      {
        name: 'textChange',
        type: 'EditorTextChangeEvent',
        description: '',
      },
      {
        name: 'editorFocus',
        type: 'void',
        description: '',
      },
      {
        name: 'editorBlur',
        type: 'void',
        description: '',
      },
      {
        name: 'editorReady',
        type: 'void',
        description: '',
      },
    ],
  },
  EditorSlashMenuComponent: {
    className: 'EditorSlashMenuComponent',
    selector: 'hk-editor-slash-menu',
    description:
      "Notion-style slash-command popup. Renders the filtered command list as a DaisyUI `menu`, supports keyboard navigation (Up / Down / Enter / Escape), and emits `commit` when the user picks an item. The host editor owns the filter state — this component is purely presentational. Positioning is driven by the editor (via inline `top` / `left` styles on the host) so this component doesn't need floating-ui.",
    inputs: [
      {
        name: 'items',
        type: 'readonly EditorSlashCommand[]',
        description: '',
      },
      {
        name: 'activeId',
        type: 'string | null',
        default: 'null',
        description: '',
      },
    ],
    outputs: [
      {
        name: 'commit',
        type: 'EditorSlashCommand',
        description: '',
      },
      {
        name: 'hoverId',
        type: 'string',
        description: '',
      },
    ],
  },
  EditorToolbarComponent: {
    className: 'EditorToolbarComponent',
    selector: 'hk-editor-toolbar',
    description:
      "Stateless editor toolbar. Knows nothing about TipTap or editor state — the parent passes which items are active / runnable and handles command dispatch. Swappable for a custom toolbar in the future without touching the editor core. Styling uses Tailwind + DaisyUI utility classes directly so the consumer's Tailwind pipeline (which already scans library source) generates the classes. Avoids issues with inline styles being suppressed by v4's CSS pipeline.",
    inputs: [
      {
        name: 'config',
        type: 'EditorToolbarConfig',
        default: "'basic'",
        description: '',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        description: '',
      },
    ],
    outputs: [
      {
        name: 'toolbarCommand',
        type: 'EditorToolbarItem',
        description: '',
      },
    ],
  },
  InputComponent: {
    className: 'InputComponent',
    selector: 'hk-input',
    description: '',
    inputs: [
      {
        name: 'variant',
        type: 'InputVariant',
        default: "'text'",
        description: '',
      },
      {
        name: 'size',
        type: 'InputSize',
        default: "'md'",
        description: '',
      },
      {
        name: 'color',
        type: 'InputColor | null',
        default: 'null',
        description: '',
      },
      {
        name: 'placeholder',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'readonly',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'prefixText',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'suffixText',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'prefixIcon',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'suffixIcon',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'showPasswordAriaLabel',
        type: 'string',
        default: "'Show password'",
        description: '',
      },
      {
        name: 'hidePasswordAriaLabel',
        type: 'string',
        default: "'Hide password'",
        description: '',
      },
      {
        name: 'currencyConfig',
        type: 'CurrencyConfig',
        default: '{}',
        description: '',
      },
      {
        name: 'phoneConfig',
        type: 'PhoneConfig',
        default: '{}',
        description: '',
      },
      {
        name: 'percentageConfig',
        type: 'PercentageConfig',
        default: '{}',
        description: '',
      },
      {
        name: 'passwordConfig',
        type: 'PasswordConfig',
        default: '{}',
        description: '',
      },
      {
        name: 'maxlength',
        type: 'number | null',
        default: 'null',
        description: '',
      },
      {
        name: 'minlength',
        type: 'number | null',
        default: 'null',
        description: '',
      },
      {
        name: 'autocomplete',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'name',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'ariaLabel',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'ariaDescribedBy',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'ariaInvalid',
        type: 'boolean',
        default: 'false',
        description: '',
      },
    ],
    outputs: [
      {
        name: 'valueChange',
        type: 'string | number | null',
        description: '',
      },
    ],
  },
  NotificationItemComponent: {
    className: 'NotificationItemComponent',
    selector: 'hk-notification-item',
    description:
      'Per-notification renderer — internal companion to `<hk-notification-host>`. Handles per-item lifecycle: auto-dismiss timer, pause-on-hover, autofocus, action invocation. The host just iterates these. Not exported from public-api: consumers always go through `NotificationService`.',
    inputs: [
      {
        name: 'notification',
        type: 'Notification',
        description: '',
      },
      {
        name: 'labels',
        type: 'ResolvedNotificationLabels',
        description: '',
      },
    ],
    outputs: [
      {
        name: 'closed',
        type: 'NotificationDismissReason',
        description: '',
      },
    ],
  },
  PdfViewerComponent: {
    className: 'PdfViewerComponent',
    selector: 'hk-pdf-viewer',
    description:
      "Lazy-loading PDF viewer built on Mozilla's PDF.js (`pdfjs-dist`). Renders any PDF source (URL, `Uint8Array`, or `Blob`) with a customizable toolbar, sidebar (thumbnails + bookmarks), text selection, search, print, and download. Configuration is split between two surfaces: - **`[src]`** (this component's input) — the document source. Volatile, often signal-driven (route params, file uploads, list selection). - **`[config]`** — stable per-instance config + lifecycle callbacks. Build with `createPdfViewer({...})` and pass `controller.config()` here. Imperative actions (navigation, zoom, search, print, download) are methods on the `PdfViewerController` returned by `createPdfViewer()` — call them directly from your component class without `@ViewChild`.",
    inputs: [
      {
        name: 'src',
        type: 'PdfDocumentSource',
        description:
          'The PDF document source. Accepts a URL string, a `Uint8Array` of bytes, or a `Blob` (e.g. from a `<input type="file">`). When this changes the viewer reloads the document.',
      },
      {
        name: 'config',
        type: 'PdfViewerConfig',
        description:
          'Configuration object — pass `controller.config()` from a `createPdfViewer({...})` call. See `PdfViewerConfig` for the full shape.',
      },
      {
        name: 'title',
        type: 'string',
        default: "''",
        description:
          "Optional headline shown above the page card in `layout: 'preview'`. Ignored in the default layout. Plain text — no markup.",
      },
      {
        name: 'subtitle',
        type: 'string',
        default: "''",
        description:
          "Optional subtitle shown under the title in `layout: 'preview'` (e.g. the document section or breadcrumb). Ignored in the default layout.",
      },
    ],
    outputs: [],
  },
  SelectComponent: {
    className: 'SelectComponent',
    selector: 'hk-select',
    description: '',
    inputs: [
      {
        name: 'id',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'options',
        type: 'SelectOption[]',
        default: '[]',
        description: '',
      },
      {
        name: 'allowClear',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'virtualScroll',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'enableSearch',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'placeholder',
        type: 'string',
        default: "'Select an option'",
        description: '',
      },
      {
        name: 'searchPlaceholder',
        type: 'string',
        default: "'Search options...'",
        description: '',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'multiple',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'maxSelectedItems',
        type: 'number | null',
        default: 'null',
        description: '',
      },
      {
        name: 'showSelectAll',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'chipDisplay',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'maxChipsVisible',
        type: 'number',
        default: '3',
        description: '',
      },
      {
        name: 'selectAllLabel',
        type: 'string',
        default: "'Select All'",
        description: '',
      },
      {
        name: 'clearAllLabel',
        type: 'string',
        default: "'Clear All'",
        description: '',
      },
      {
        name: 'selectedSuffix',
        type: 'string',
        default: "'selected'",
        description: '',
      },
      {
        name: 'noOptionsFoundLabel',
        type: 'string',
        default: "'No options found'",
        description: '',
      },
      {
        name: 'clearSearchLabel',
        type: 'string',
        default: "'Clear search'",
        description: '',
      },
      {
        name: 'noOptionsAvailableLabel',
        type: 'string',
        default: "'No options available'",
        description: '',
      },
      {
        name: 'size',
        type: 'SelectSize',
        default: "'md'",
        description: '',
      },
      {
        name: 'color',
        type: 'SelectColor | null',
        default: 'null',
        description: '',
      },
    ],
    outputs: [
      {
        name: 'selectionChange',
        type: 'SelectOption | SelectOption[] | null',
        description: '',
      },
      {
        name: 'searchChange',
        type: 'string',
        description: '',
      },
      {
        name: 'dropdownToggle',
        type: 'boolean',
        description: '',
      },
    ],
  },
  StepperComponent: {
    className: 'StepperComponent',
    selector: 'hk-stepper',
    description: '',
    inputs: [
      {
        name: 'showStepIndicator',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'showCard',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'animateContent',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'previousButtonText',
        type: 'string',
        default: "'Previous'",
        description: '',
      },
      {
        name: 'nextButtonText',
        type: 'string',
        default: "'Next'",
        description: '',
      },
      {
        name: 'completeButtonText',
        type: 'string',
        default: "'Complete'",
        description: '',
      },
      {
        name: 'optionalLabel',
        type: 'string',
        default: "'(Optional)'",
        description: '',
      },
    ],
    outputs: [
      {
        name: 'completed',
        type: 'void',
        description: '',
      },
      {
        name: 'stepChange',
        type: '{ previousIndex: number; currentIndex: number }',
        description: '',
      },
    ],
  },
  TabGroupComponent: {
    className: 'TabGroupComponent',
    selector: 'hk-tab-group',
    description: '',
    inputs: [
      {
        name: 'activeIndex',
        type: 'import("@angular/core").InputSignal<number>',
        default: '0',
        description: 'The index of the initially active tab',
      },
      {
        name: 'selectionMode',
        type: "'follow' | 'explicit'",
        default: "'explicit'",
        description: "Selection mode: 'follow' activates on focus, 'explicit' requires click/enter",
      },
      {
        name: 'orientation',
        type: "'horizontal' | 'vertical'",
        default: "'horizontal'",
        description: 'Orientation of the tab list',
      },
      {
        name: 'variant',
        type: "'lift' | 'box' | 'border'",
        default: "'lift'",
        description:
          "Visual variant of the tab list (horizontal mode only): - `'lift'` (default) — tabs attach to a content panel below, with the active tab \"lifted\" visually. - `'box'` — pill/box-style tabs, panel sits in a bordered card below. - `'border'` — minimal underline-style tabs with a panel below. In **vertical** mode, the variant is ignored — vertical renders as a unified card with a sidebar tab list and a content panel area. The daisyUI tab variants (lift / box / border) are all horizontal-by-design and don't translate cleanly to a side-by-side layout, so the vertical mode uses its own sidebar pattern.",
      },
      {
        name: 'wrap',
        type: 'import("@angular/core").InputSignal<boolean>',
        default: 'true',
        description: 'Whether keyboard navigation should wrap',
      },
    ],
    outputs: [],
  },
  TableColumnVisibilityComponent: {
    className: 'TableColumnVisibilityComponent',
    selector: 'hk-table-column-visibility',
    description: '',
    inputs: [
      {
        name: 'labels',
        type: 'ColumnVisibilityLabels',
        default: '{}',
        description: '',
      },
    ],
    outputs: [
      {
        name: 'toggleColumn',
        type: 'string',
        description: '',
      },
      {
        name: 'showAll',
        type: 'void',
        description: '',
      },
      {
        name: 'hideAll',
        type: 'void',
        description: '',
      },
      {
        name: 'resetEmitter',
        type: 'void',
        description: '',
      },
    ],
  },
  TableComponent: {
    className: 'TableComponent',
    selector: 'hk-table',
    description: '',
    inputs: [
      {
        name: 'data',
        type: 'readonly T[] | null',
        default: 'null',
        description: '',
      },
      {
        name: 'paginationOptions',
        type: 'PaginationOptions | null',
        default: 'null',
        description: '',
      },
      {
        name: 'showFirstLastButtons',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'hidePageSize',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'showPageSizeOptions',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'loading',
        type: 'boolean',
        default: 'false',
        description: 'Show loading skeleton overlay',
      },
      {
        name: 'error',
        type: 'string | null',
        default: 'null',
        description: 'Error message to display instead of table data',
      },
      {
        name: 'emptyMessage',
        type: 'string',
        default: "'No data available'",
        description: "Custom empty state message (default: 'No data available')",
      },
    ],
    outputs: [
      {
        name: 'selectionChange',
        type: 'readonly T[]',
        description: '',
      },
      {
        name: 'pageChange',
        type: 'PageSizeChange',
        description: '',
      },
      {
        name: 'cursorChange',
        type: 'CursorPageChange',
        description: '',
      },
      {
        name: 'sortChange',
        type: 'SortChange',
        description: '',
      },
      {
        name: 'sortFieldChange',
        type: 'string',
        description: '',
      },
      {
        name: 'sortDirectionChange',
        type: "'Ascending' | 'Descending' | ''",
        description: '',
      },
      {
        name: 'globalSearchChange',
        type: 'GlobalSearchChange',
        description: '',
      },
      {
        name: 'expansionChange',
        type: '{ row: T; expanded: boolean }',
        description: '',
      },
      {
        name: 'columnResize',
        type: 'ColumnResizeEvent',
        description: '',
      },
      {
        name: 'cellEditCancel',
        type: '{ row: T; field: string }',
        description: '',
      },
      {
        name: 'columnReorder',
        type: 'ColumnReorderEvent',
        description: '',
      },
      {
        name: 'groupExpandChange',
        type: 'GroupExpandEvent',
        description: '',
      },
      {
        name: 'rowClick',
        type: 'T',
        description: '',
      },
      {
        name: 'masterDetailRowChange',
        type: 'T',
        description: '',
      },
      {
        name: 'activeRowChange',
        type: 'T | null',
        description: '',
      },
      {
        name: 'activeRowsChange',
        type: 'readonly T[]',
        description: '',
      },
    ],
  },
  TableFilterComponent: {
    className: 'TableFilterComponent',
    selector: 'hk-table-filter',
    description: '',
    inputs: [
      {
        name: 'labels',
        type: 'FilterLabels',
        default: '{}',
        description: 'Inherited filter labels (from `FieldConfig.filterLabels`). Per-column overrides via `ColumnFilter.labels` win.',
      },
    ],
    outputs: [
      {
        name: 'apply',
        type: 'FilterApplyEvent',
        description: '',
      },
      {
        name: 'closeFilter',
        type: 'void',
        description: '',
      },
    ],
  },
  TableGlobalSearchComponent: {
    className: 'TableGlobalSearchComponent',
    selector: 'hk-table-global-search',
    description: '',
    inputs: [
      {
        name: 'searchTerm',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'placeholder',
        type: 'string',
        default: "'Search all columns...'",
        description: '',
      },
      {
        name: 'showIcon',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'showClearButton',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'hasSearchTerm',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'clearAriaLabel',
        type: 'string',
        default: "'Clear search'",
        description: '',
      },
    ],
    outputs: [
      {
        name: 'searchChange',
        type: 'string',
        description: '',
      },
      {
        name: 'clear',
        type: 'void',
        description: '',
      },
    ],
  },
  TablePaginationComponent: {
    className: 'TablePaginationComponent',
    selector: 'hk-table-pagination',
    description: '',
    inputs: [
      {
        name: 'paginationOptions',
        type: 'PaginationOptions | null',
        default: 'null',
        description: '',
      },
      {
        name: 'totalItems',
        type: 'number',
        default: '0',
        description: '',
      },
      {
        name: 'showFirstLastButtons',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'hidePageSize',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'showPageSizeOptions',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'pageIndex',
        type: 'number',
        default: '0',
        description: '',
      },
      {
        name: 'pageSize',
        type: 'number',
        default: '10',
        description: '',
      },
    ],
    outputs: [
      {
        name: 'pageChange',
        type: 'PageSizeChange',
        description: '',
      },
      {
        name: 'cursorChange',
        type: 'CursorPageChange',
        description: '',
      },
    ],
  },
  TabPanelComponent: {
    className: 'TabPanelComponent',
    selector: 'hk-tab-panel',
    description: '',
    inputs: [
      {
        name: 'value',
        type: 'string',
        description: 'Unique value identifier for this tab panel',
      },
      {
        name: 'label',
        type: 'import("@angular/core").InputSignal<string>',
        default: "''",
        description: 'Label displayed on the tab button',
      },
      {
        name: 'icon',
        type: 'string | undefined',
        default: 'undefined',
        description: 'Optional icon (reserved for future custom icon support)',
      },
      {
        name: 'disabled',
        type: 'import("@angular/core").InputSignal<boolean>',
        default: 'false',
        description: 'Whether the tab is disabled',
      },
    ],
    outputs: [],
  },
  TimepickerComponent: {
    className: 'TimepickerComponent',
    selector: 'hk-timepicker',
    description: '',
    inputs: [
      {
        name: 'placeholder',
        type: 'string',
        default: "'Select Time'",
        description: '',
      },
      {
        name: 'hourLabel',
        type: 'string',
        default: "'Hr'",
        description: '',
      },
      {
        name: 'minuteLabel',
        type: 'string',
        default: "'Min'",
        description: '',
      },
      {
        name: 'secondLabel',
        type: 'string',
        default: "'Sec'",
        description: '',
      },
      {
        name: 'nowLabel',
        type: 'string',
        default: "'Now'",
        description: '',
      },
      {
        name: 'clearLabel',
        type: 'string',
        default: "'Clear'",
        description: '',
      },
      {
        name: 'closeLabel',
        type: 'string',
        default: "'Close'",
        description: '',
      },
      {
        name: 'requiredError',
        type: 'string',
        default: "'This field is required.'",
        description: '',
      },
      {
        name: 'minTimeError',
        type: 'string',
        default: "'Time must be after'",
        description: '',
      },
      {
        name: 'maxTimeError',
        type: 'string',
        default: "'Time must be before'",
        description: '',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'use24Hour',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'showSeconds',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'minuteStep',
        type: 'number',
        default: '1',
        description: '',
      },
      {
        name: 'secondStep',
        type: 'number',
        default: '1',
        description: '',
      },
      {
        name: 'closeOnSelect',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'showClearButton',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'showNowButton',
        type: 'boolean',
        default: 'true',
        description: '',
      },
      {
        name: 'dropdownPosition',
        type: 'TimepickerPosition',
        default: "'bottom-left'",
        description: '',
      },
      {
        name: 'minWidth',
        type: 'string',
        default: "'16rem'",
        description: '',
      },
      {
        name: 'required',
        type: 'boolean',
        default: 'false',
        description: '',
      },
      {
        name: 'name',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'formControlName',
        type: 'string',
        default: "''",
        description: '',
      },
      {
        name: 'minTime',
        type: 'string | undefined',
        description: '',
      },
      {
        name: 'maxTime',
        type: 'string | undefined',
        description: '',
      },
      {
        name: 'clockFace',
        type: 'boolean',
        default: 'false',
        description: '',
      },
    ],
    outputs: [
      {
        name: 'timeChange',
        type: 'TimepickerEvent',
        description: '',
      },
      {
        name: 'pickerOpened',
        type: 'void',
        description: '',
      },
      {
        name: 'pickerClosed',
        type: 'void',
        description: '',
      },
    ],
  },
  TreeComponent: {
    className: 'TreeComponent',
    selector: 'hk-tree',
    description: '',
    inputs: [],
    outputs: [
      {
        name: 'filterChange',
        type: 'TreeFilterEvent',
        description: 'Emitted when filter changes',
      },
    ],
  },
  VirtualScrollerComponent: {
    className: 'VirtualScrollerComponent',
    selector: 'hk-virtual-scroller',
    description:
      'Virtualized list/grid renderer backed by `@angular/cdk/scrolling`. Renders only the rows in (or near) the viewport — use it for lists of thousands of items where rendering everything would tank performance. **Slots** — provide content via named templates: - `<ng-template #item let-item let-i="index">` — required, renders each row. - `<ng-template #loader>` — optional, shown for `null` placeholder items in `lazy` mode. - `<ng-template #header>` / `<ng-template #footer>` — optional, rendered above/below the list. **Lazy loading** — set `[lazy]="true"` and seed `items` with `null` placeholders for the un-loaded rows. As the user scrolls, `(lazyLoad)` fires with the index range that needs data — fetch and patch those slots in your `items` array. Each `{first, rows}` range is emitted **at most once** (dedup via internal cache). **Grid mode** — set `numColumns > 1` to lay items out in N-column rows. `itemSize` is the row height in this mode.',
    inputs: [
      {
        name: 'items',
        type: 'readonly (T | null)[]',
        default: '[]',
        description:
          'Data array. In `lazy` mode, use `null` for not-yet-loaded slots and the scroller will emit `lazyLoad` for those index ranges as they become visible.',
      },
      {
        name: 'itemSize',
        type: 'number',
        description:
          'Item size in px — row height for vertical, column width for horizontal. Must match the actual rendered size; mismatches break virtualization math. Required.',
      },
      {
        name: 'orientation',
        type: 'VirtualScrollerOrientation',
        default: "'vertical'",
        description: "Scroll axis. Default: `'vertical'`.",
      },
      {
        name: 'numColumns',
        type: 'number',
        default: '1',
        description: 'Number of columns (vertical orientation). `>1` enables grid mode. Default: `1`.',
      },
      {
        name: 'viewportHeight',
        type: 'string',
        default: "'400px'",
        description: "Viewport height (CSS value). Default: `'400px'`.",
      },
      {
        name: 'viewportWidth',
        type: 'string',
        default: "'100%'",
        description: "Viewport width (CSS value). Default: `'100%'`.",
      },
      {
        name: 'scrollDelay',
        type: 'number',
        default: '0',
        description: 'Debounce (ms) before `scrolled` / `lazyLoad` fire. Default: `0`.',
      },
      {
        name: 'minBufferPx',
        type: 'number',
        default: '100',
        description: 'Minimum off-screen buffer to render ahead, in px. Default: `100`.',
      },
      {
        name: 'maxBufferPx',
        type: 'number',
        default: '200',
        description: 'Maximum off-screen buffer, in px. CDK keeps rendered range between min/max. Default: `200`.',
      },
      {
        name: 'lazy',
        type: 'boolean',
        default: 'false',
        description: 'Enable lazy-load mode: `null` slots in `items` cause `lazyLoad` to fire. Default: `false`.',
      },
      {
        name: 'loading',
        type: 'boolean',
        default: 'false',
        description: 'Show a loading state on the viewport (e.g. while fetching the first page). Default: `false`.',
      },
      {
        name: 'containerClass',
        type: 'string',
        default: "''",
        description: 'Extra classes applied to the scroll viewport container.',
      },
      {
        name: 'itemClass',
        type: 'string',
        default: "''",
        description: 'Extra classes applied to each item wrapper.',
      },
    ],
    outputs: [
      {
        name: 'scrolled',
        type: 'VirtualScrollerScrollEvent',
        description: 'Fires on scroll. Emits the current scroll offset and rendered range.',
      },
      {
        name: 'lazyLoad',
        type: 'VirtualScrollerLazyLoadEvent',
        description:
          'Fires when an un-loaded range becomes visible (lazy mode only). Each range is emitted at most once per session — patch `items` with real data and the same range will not re-fire.',
      },
      {
        name: 'scrollIndexChange',
        type: 'number',
        description: 'Fires when the topmost rendered index changes.',
      },
    ],
  },
} as const;

export const API_DOCS: Record<keyof typeof _API_DOCS, ComponentApi> = _API_DOCS;

export type ApiComponentName = keyof typeof _API_DOCS;
